In [ ]:
# Import the necessary libraries
import pandas as pd

# Data Analysis of Car Contracts
This notebook analyzes the car contracts dataset to extract insights and perform evaluations.

In [ ]:
# Load the dataset
# Uncomment the appropriate line based on the file location
# df = pd.read_csv('../data/sample_car_contract.csv')
# df = pd.read_csv('C:/Users/Admin/Downloads/sample_car_contracts.csv')
df = pd.read_csv('../data/sample_car_contracts.csv')
df.head()  # Display the first few rows of the dataset

,id,customer_name,contract_type,vehicle_type,monthly_emi,interest_rate,tenure_months,clause_summary,risk_flag,issue_type,recommended_action
0,1,Rahul Mehta,Car Loan,Sedan,18500,9.5,48,Prepayment allowed only after 24 months with 5...,medium,High prepayment charges,Highlight prepayment penalty to user and sugge...
1,2,Anita Rao,Car Lease,SUV,22000,0.0,36,Lessee must pay for all maintenance and insurance,low,Standard maintenance clause,"No action, just explain maintenance responsibi..."
2,3,James Wilson,Car Loan,Hatchback,14500,11.2,60,Late payment fee of 3% per month on outstandin...,high,Aggressive late fee,Flag clause and suggest user request cap on la...
3,4,Meena Iyer,Car Lease,Sedan,21000,0.0,24,"Excess mileage charge of ₹12 per km over 15,00...",medium,High excess mileage rate,Warn user about extra mileage charges and reco...
4,5,Arjun Patel,Car Loan,SUV,27500,10.8,72,Floating interest rate linked to lender's inte...,high,Unclear interest benchmark,Explain floating rate risk and suggest asking ...

In [ ]:
# Display information about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  12 non-null     int64
 1   customer_name       12 non-null     object
 2   contract_type       12 non-null     object
 3   vehicle_type        12 non-null     object
 4   monthly_emi         12 non-null     int64
 5   interest_rate       12 non-null     float64
 6   tenure_months       12 non-null     int64
 7   clause_summary      12 non-null     object
 8   risk_flag           12 non-null     object
 9   issue_type          12 non-null     object
 10  recommended_action  12 non-null     object
dtypes: float64(1), int64(3), object(7)
memory usage: 1.2+ KB

In [ ]:
# Get descriptive statistics of the dataset
df.describe()

              id   monthly_emi  interest_rate  tenure_months
count  12.000000     12.000000      12.000000       12.00000
mean    6.500000  20975.000000       5.233333       47.00000
std     3.605551   5257.743208       5.536217       17.50844
min     1.000000  13200.000000       0.000000       24.00000
25%     3.750000  18000.000000       0.000000       36.00000
50%     6.500000  20250.000000       4.450000       45.00000
75%     9.250000  24750.000000      10.125000       51.00000
max    12.000000  30500.000000      12.500000       84.00000

In [ ]:
# Analyze the distribution of contract types and risk flags
print("Contract type counts:")
print(df['contract_type'].value_counts())

print("\nRisk flag counts:")
print(df['risk_flag'].value_counts())

# Filter and display high-risk records
high_risk = df[df['risk_flag'].str.lower() == 'high']
print("\nHigh-risk records:")
high_risk

Contract type counts:
contract_type
Car Loan     6
Car Lease    6
Name: count, dtype: int64

Risk flag counts:
risk_flag
high      5
medium    4
low       3
Name: count, dtype: int64

High-risk records:

,id,customer_name,contract_type,vehicle_type,monthly_emi,interest_rate,tenure_months,clause_summary,risk_flag,issue_type,recommended_action
2,3,James Wilson,Car Loan,Hatchback,14500,11.2,60,Late payment fee of 3% per month on outstandin...,high,Aggressive late fee,Flag clause and suggest user request cap on la...
4,5,Arjun Patel,Car Loan,SUV,27500,10.8,72,Floating interest rate linked to lender's inte...,high,Unclear interest benchmark,Explain floating rate risk and suggest asking ...
5,6,Sana Khan,Car Lease,Hatchback,16500,0.0,36,Early termination fee equal to 6 months of EMI,high,Heavy early termination penalty,Flag as risky and suggest negotiating lower te...
8,9,David Roy,Car Loan,SUV,30500,12.5,84,Mandatory bundled insurance from lender at non...,high,Forced insurance bundling,Flag as unfair tying and suggest independent i...
11,12,Imran Ali,Car Lease,SUV,24500,0.0,42,Lessor can repossess vehicle after 2 consecuti...,high,Aggressive repossession clause,Strongly warn user and recommend clarification...

In [ ]:
# Display the shape of the dataset
df.shape

(12, 11)

In [ ]:
# Display the columns in the dataset
df.columns

Index(['id', 'customer_name', 'contract_type', 'vehicle_type', 'monthly_emi',
       'interest_rate', 'tenure_months', 'clause_summary', 'risk_flag',
       'issue_type', 'recommended_action'],
      dtype='object')

In [ ]:
# Check for missing values in the dataset
df.isnull().sum()

id                    0
customer_name         0
contract_type         0
vehicle_type          0
monthly_emi           0
interest_rate         0
tenure_months         0
clause_summary        0
risk_flag             0
issue_type            0
recommended_action    0
dtype: int64

In [ ]:
# Display specific columns of interest
df[['id','customer_name','contract_type']].head(10)

   id customer_name contract_type
0   1   Rahul Mehta      Car Loan
1   2     Anita Rao     Car Lease
2   3  James Wilson      Car Loan
3   4    Meena Iyer     Car Lease
4   5   Arjun Patel      Car Loan
5   6     Sana Khan     Car Lease
6   7   Vikram Shah      Car Loan
7   8    Neha Singh     Car Lease
8   9     David Roy      Car Loan
9  10   Kiran Kumar     Car Lease

In [ ]:
# Get descriptive statistics of numerical columns
df[['monthly_emi','interest_rate','tenure_months']].describe()

        monthly_emi  interest_rate  tenure_months
count     12.000000      12.000000       12.00000
mean   20975.000000       5.233333       47.00000
std     5257.743208       5.536217       17.50844
min    13200.000000       0.000000       24.00000
25%    18000.000000       0.000000       36.00000
50%    20250.000000       4.450000       45.00000
75%    24750.000000      10.125000       51.00000
max    30500.000000      12.500000       84.00000

In [ ]:
# Analyze value counts for various columns
print("Contract Type Value counts \n",df["contract_type"].value_counts())

print("\n Veichle Type Value counts \n",df["vehicle_type"].value_counts())

print("\n Interet Type Value counts \n",df["interest_rate"].value_counts())

Contract Type Value counts
 contract_type
Car Loan     6
Car Lease    6
Name: count, dtype: int64

 Veichle Type Value counts
 vehicle_type
Sedan        4
SUV          4
Hatchback    3
EV           1
Name: count, dtype: int64

 Interet Type Value counts
 interest_rate
0.0     6
9.5     1
11.2    1
10.8    1
8.9     1
12.5    1
9.9     1
Name: count, dtype: int64

In [ ]:
# Analyze the average interest rate based on risk flag
print("Average of the risk flag " , df.groupby('risk_flag')['interest_rate'].mean())

Average of the risk flag  risk_flag
high      6.900000
low       2.966667
medium    4.850000
Name: interest_rate, dtype: float64

In [ ]:
# Display the columns in the dataset again
df.columns

Index(['id', 'customer_name', 'contract_type', 'vehicle_type', 'monthly_emi',
       'interest_rate', 'tenure_months', 'clause_summary', 'risk_flag',
       'issue_type', 'recommended_action'],
      dtype='object')

In [ ]:
# Display the columns in the dataset once more
df.columns

Index(['id', 'customer_name', 'contract_type', 'vehicle_type', 'monthly_emi',
       'interest_rate', 'tenure_months', 'clause_summary', 'risk_flag',
       'issue_type', 'recommended_action'],
      dtype='object')

In [ ]:
# Separate numerical and categorical columns
numeric_columns = df.select_dtypes(include=["int64","float"])
print("Numerical Columns are : \n", numeric_columns)

categerical_columns = df.select_dtypes(include=["object"])
print("\n Categerical Columns are : \n", categerical_columns)

Numerical Columns are :
     id  monthly_emi  interest_rate  tenure_months
0    1        18500            9.5             48
1    2        22000            0.0             36
2    3        14500           11.2             60
3    4        21000            0.0             24
4    5        27500           10.8             72
5    6        16500            0.0             36
6    7        19500            8.9             36
7    8        25500            0.0             48
8    9        30500           12.5             84
9   10        18500            0.0             30
10  11        13200            9.9             48
11  12        24500            0.0             42

 Categerical Columns are :
    customer_name contract_type vehicle_type  \
0    Rahul Mehta      Car Loan        Sedan
1      Anita Rao     Car Lease          SUV
2   James Wilson      Car Loan    Hatchback
3     Meena Iyer     Car Lease        Sedan
4    Arjun Patel      Car Loan          SUV
5      Sana Khan     Car Lease    Hatchback
6    Vikram Shah      Car Loan        Sedan
7     Neha Singh     Car Lease           EV
8      David Roy      Car Loan          SUV
9    Kiran Kumar     Car Lease        Sedan
10   Pratima Das      Car Loan    Hatchback
11     Imran Ali     Car Lease          SUV

                                       clause_summary risk_flag  \
0   Prepayment allowed only after 24 months with 5...    medium
1   Lessee must pay for all maintenance and insurance       low
2   Late payment fee of 3% per month on outstandin...      high
3   Excess mileage charge of ₹12 per km over 15,00...    medium
4   Floating interest rate linked to lender's inte...      high
5      Early termination fee equal to 6 months of EMI      high
6              No foreclosure charges after 12 months       low
7   Battery warranty covered only for 24 months or...    medium
8   Mandatory bundled insurance from lender at non...      high
9   Security deposit of 3 EMIs, refundable at end ...       low
10  Processing fee of 1.5% of loan amount, non-ref...    medium
11  Lessor can repossess vehicle after 2 consecuti...      high

                          issue_type  \
0            High prepayment charges
1        Standard maintenance clause
2                Aggressive late fee
3           High excess mileage rate
4         Unclear interest benchmark
5    Heavy early termination penalty
6   User friendly foreclosure policy
7        Limited EV battery warranty
8          Forced insurance bundling
9          Standard security deposit
10               High processing fee
11    Aggressive repossession clause

                                   recommended_action
0   Highlight prepayment penalty to user and sugge...
1   No action, just explain maintenance responsibi...
2   Flag clause and suggest user request cap on la...
3   Warn user about extra mileage charges and reco...
4   Explain floating rate risk and suggest asking ...
5   Flag as risky and suggest negotiating lower te...
6         Mark as positive clause, no action required
7   Warn user about battery risk and suggest exten...
8   Flag as unfair tying and suggest independent i...
9              Explain condition for refund, low risk
10  Highlight cost and suggest user negotiate lowe...
11  Strongly warn user and recommend clarification...