# Contract Data Extraction & Cleaning

### STEP 1: Import Required Libraries

In [24]:
import pandas as pd
import re
from pathlib import Path

### STEP 2: Load Dataset

In [25]:
df=pd.read_csv('../data/sample_emails.csv')

df.head()

,id,sender,subject,body,priority,label
0,1,arjun.mehta@example.com,Request for EMI Clarification,"Hello Team, I need clarification regarding my ...",Medium,Query
1,2,pooja.reddy@example.com,Complaint on Processing Fee,I was charged an additional processing fee tha...,High,Complaint
2,3,rahul.sharma@example.com,Battery Warranty Concern,"Since my vehicle is an EV, I want clarity on t...",Medium,Query
3,4,neha.kapoor@example.com,Interest Rate Mismatch,The interest rate shown in the portal is diffe...,High,Dispute
4,5,vikram.singh@example.com,Request for Prepayment Information,Please share the exact charges and rules appli...,Low,Request

## STEP 3: View Columns

In [26]:
df.columns

Index(['id', 'sender', 'subject', 'body', 'priority', 'label'], dtype='object')

### STEP 4: Cleaning Phone Numbers

Phone numbers often contain spaces, dashes, or extra characters.
We remove everything except digits.

Example: "987-654 3210" → "9876543210"

In [27]:
def clean_phone(p):
    return re.sub(r"\D", "", str(p))

# Create a sample phone column for demonstration since it doesn't exist in emails data
df["phone_no_sample"] = "555-123-4567"
df["phone_no_clean"] = df["phone_no_sample"].apply(clean_phone)
df["phone_no_clean"].head()

0    5551234567
1    5551234567
2    5551234567
3    5551234567
4    5551234567
Name: phone_no_clean, dtype: object

### STEP 5: Cleaning Email IDs

In [28]:
df["email_id_clean"] = df["sender"].str.lower()
df["email_id_clean"].head()

0     arjun.mehta@example.com
1     pooja.reddy@example.com
2    rahul.sharma@example.com
3     neha.kapoor@example.com
4    vikram.singh@example.com
Name: email_id_clean, dtype: object

### STEP 6: Cleaning Text Columns

In [29]:
def clean_text(s):
    if pd.isna(s):
        return ""
    s = str(s)
    s = re.sub(r"\s+", " ", s).strip()
    return s

df["clause_summary_clean"] = df["body"].apply(clean_text)
df["clause_summary_clean"].head()

0    Hello Team, I need clarification regarding my ...
1    I was charged an additional processing fee tha...
2    Since my vehicle is an EV, I want clarity on t...
3    The interest rate shown in the portal is diffe...
4    Please share the exact charges and rules appli...
Name: clause_summary_clean, dtype: object

We convert EMI, interest rate, and tenure into numeric types to avoid errors in analysis.

In [30]:
# Create sample numeric columns for demonstration (not in original email data)
df["monthly_emi"] = pd.Series([5000.0, 6000.0, 5500.0, 7000.0, 6500.0] + [0.0] * (len(df) - 5))
df["interest_rate"] = pd.Series([8.5, 9.2, 8.8, 9.5, 8.0] + [0.0] * (len(df) - 5))
df["tenure_months"] = pd.Series([60, 48, 72, 60, 48] + [0] * (len(df) - 5))

df[["monthly_emi", "interest_rate", "tenure_months"]].head()

   monthly_emi  interest_rate  tenure_months
0       5000.0            8.5             60
1       6000.0            9.2             48
2       5500.0            8.8             72
3       7000.0            9.5             60
4       6500.0            8.0             48

### STEP 8: Show Cleaned Columns

In [32]:
cleaned_df = df[[
    "id",
    "sender",
    "email_id_clean",
    "phone_no_clean",
    "priority",
    "label",
    "monthly_emi",
    "interest_rate",
    "tenure_months",
    "clause_summary_clean"
]]

cleaned_df.head()

,id,sender,email_id_clean,phone_no_clean,priority,label,monthly_emi,interest_rate,tenure_months,clause_summary_clean
0,1,arjun.mehta@example.com,arjun.mehta@example.com,5551234567,Medium,Query,5000.0,8.5,60,"Hello Team, I need clarification regarding my ..."
1,2,pooja.reddy@example.com,pooja.reddy@example.com,5551234567,High,Complaint,6000.0,9.2,48,I was charged an additional processing fee tha...
2,3,rahul.sharma@example.com,rahul.sharma@example.com,5551234567,Medium,Query,5500.0,8.8,72,"Since my vehicle is an EV, I want clarity on t..."
3,4,neha.kapoor@example.com,neha.kapoor@example.com,5551234567,High,Dispute,7000.0,9.5,60,The interest rate shown in the portal is diffe...
4,5,vikram.singh@example.com,vikram.singh@example.com,5551234567,Low,Request,6500.0,8.0,48,Please share the exact charges and rules appli...

### STEP 9: Save Cleaned Dataset

In [34]:
output_path = Path("../data/sample_emails_cleaned.csv")
output_path.parent.mkdir(parents=True, exist_ok=True)
cleaned_df.to_csv(output_path, index=False)

print("Cleaned file saved to:", output_path.resolve())

Cleaned file saved to: C:\Users\muppa\OneDrive\Desktop\Infosys Project\infosys-carlease-contract-ai-group2\data\sample_emails_cleaned.csv