In [1]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\h6jyo\appdata\roaming\python\python313\site-packages (2.3.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\h6jyo\appdata\roaming\python\python313\site-packages (from pandas) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\h6jyo\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\h6jyo\appdata\roaming\python\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\h6jyo\appdata\roaming\python\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\h6jyo\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

df = pd.read_csv('../data/sample_car_contracts.csv')
df.head()

,id,customer_name,contract_type,vehicle_type,monthly_emi,interest_rate,tenure_months,clause_summary,risk_flag,issue_type,recommended_action
0,1,Rahul Mehta,Car Loan,Sedan,18500,9.5,48,Prepayment allowed only after 24 months with 5...,medium,High prepayment charges,Highlight prepayment penalty to user and sugge...
1,2,Anita Rao,Car Lease,SUV,22000,0.0,36,Lessee must pay for all maintenance and insurance,low,Standard maintenance clause,"No action, just explain maintenance responsibi..."
2,3,James Wilson,Car Loan,Hatchback,14500,11.2,60,Late payment fee of 3% per month on outstandin...,high,Aggressive late fee,Flag clause and suggest user request cap on la...
3,4,Meena Iyer,Car Lease,Sedan,21000,0.0,24,"Excess mileage charge of ₹12 per km over 15,00...",medium,High excess mileage rate,Warn user about extra mileage charges and reco...
4,5,Arjun Patel,Car Loan,SUV,27500,10.8,72,Floating interest rate linked to lender's inte...,high,Unclear interest benchmark,Explain floating rate risk and suggest asking ...

In [3]:
df.shape

(12, 11)

In [4]:
df.columns

Index(['id', 'customer_name', 'contract_type', 'vehicle_type', 'monthly_emi',
       'interest_rate', 'tenure_months', 'clause_summary', 'risk_flag',
       'issue_type', 'recommended_action'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  12 non-null     int64
 1   customer_name       12 non-null     object
 2   contract_type       12 non-null     object
 3   vehicle_type        12 non-null     object
 4   monthly_emi         12 non-null     int64
 5   interest_rate       12 non-null     float64
 6   tenure_months       12 non-null     int64
 7   clause_summary      12 non-null     object
 8   risk_flag           12 non-null     object
 9   issue_type          12 non-null     object
 10  recommended_action  12 non-null     object
dtypes: float64(1), int64(3), object(7)
memory usage: 1.2+ KB

In [7]:
df[['id','customer_name','contract_type','vehicle_type','monthly_emi','interest_rate','tenure_months','clause_summary','risk_flag','recommended_action','issue_type']]

,id,customer_name,contract_type,vehicle_type,monthly_emi,interest_rate,tenure_months,clause_summary,risk_flag,recommended_action,issue_type
0,1,Rahul Mehta,Car Loan,Sedan,18500,9.5,48,Prepayment allowed only after 24 months with 5...,medium,Highlight prepayment penalty to user and sugge...,High prepayment charges
1,2,Anita Rao,Car Lease,SUV,22000,0.0,36,Lessee must pay for all maintenance and insurance,low,"No action, just explain maintenance responsibi...",Standard maintenance clause
2,3,James Wilson,Car Loan,Hatchback,14500,11.2,60,Late payment fee of 3% per month on outstandin...,high,Flag clause and suggest user request cap on la...,Aggressive late fee
3,4,Meena Iyer,Car Lease,Sedan,21000,0.0,24,"Excess mileage charge of ₹12 per km over 15,00...",medium,Warn user about extra mileage charges and reco...,High excess mileage rate
4,5,Arjun Patel,Car Loan,SUV,27500,10.8,72,Floating interest rate linked to lender's inte...,high,Explain floating rate risk and suggest asking ...,Unclear interest benchmark
5,6,Sana Khan,Car Lease,Hatchback,16500,0.0,36,Early termination fee equal to 6 months of EMI,high,Flag as risky and suggest negotiating lower te...,Heavy early termination penalty
6,7,Vikram Shah,Car Loan,Sedan,19500,8.9,36,No foreclosure charges after 12 months,low,"Mark as positive clause, no action required",User friendly foreclosure policy
7,8,Neha Singh,Car Lease,EV,25500,0.0,48,Battery warranty covered only for 24 months or...,medium,Warn user about battery risk and suggest exten...,Limited EV battery warranty
8,9,David Roy,Car Loan,SUV,30500,12.5,84,Mandatory bundled insurance from lender at non...,high,Flag as unfair tying and suggest independent i...,Forced insurance bundling
9,10,Kiran Kumar,Car Lease,Sedan,18500,0.0,30,"Security deposit of 3 EMIs, refundable at end ...",low,"Explain condition for refund, low risk",Standard security deposit
10,11,Pratima Das,Car Loan,Hatchback,13200,9.9,48,"Processing fee of 1.5% of loan amount, non-ref...",medium,Highlight cost and suggest user negotiate lowe...,High processing fee
11,12,Imran Ali,Car Lease,SUV,24500,0.0,42,Lessor can repossess vehicle after 2 consecuti...,high,Strongly warn user and recommend clarification...,Aggressive repossession clause

In [8]:
df[['id','clause_summary']].head()

   id                                     clause_summary
0   1  Prepayment allowed only after 24 months with 5...
1   2  Lessee must pay for all maintenance and insurance
2   3  Late payment fee of 3% per month on outstandin...
3   4  Excess mileage charge of ₹12 per km over 15,00...
4   5  Floating interest rate linked to lender's inte...

In [10]:
df[['monthly_emi','interest_rate','tenure_months']].describe()

        monthly_emi  interest_rate  tenure_months
count     12.000000      12.000000       12.00000
mean   20975.000000       5.233333       47.00000
std     5257.743208       5.536217       17.50844
min    13200.000000       0.000000       24.00000
25%    18000.000000       0.000000       36.00000
50%    20250.000000       4.450000       45.00000
75%    24750.000000      10.125000       51.00000
max    30500.000000      12.500000       84.00000

In [3]:
import pandas as pd

df = pd.read_csv('../data/sample_car_contracts.csv')
df.head()

,id,customer_name,contract_type,vehicle_type,monthly_emi,interest_rate,tenure_months,clause_summary,risk_flag,issue_type,recommended_action
0,1,Rahul Mehta,Car Loan,Sedan,18500,9.5,48,Prepayment allowed only after 24 months with 5...,medium,High prepayment charges,Highlight prepayment penalty to user and sugge...
1,2,Anita Rao,Car Lease,SUV,22000,0.0,36,Lessee must pay for all maintenance and insurance,low,Standard maintenance clause,"No action, just explain maintenance responsibi..."
2,3,James Wilson,Car Loan,Hatchback,14500,11.2,60,Late payment fee of 3% per month on outstandin...,high,Aggressive late fee,Flag clause and suggest user request cap on la...
3,4,Meena Iyer,Car Lease,Sedan,21000,0.0,24,"Excess mileage charge of ₹12 per km over 15,00...",medium,High excess mileage rate,Warn user about extra mileage charges and reco...
4,5,Arjun Patel,Car Loan,SUV,27500,10.8,72,Floating interest rate linked to lender's inte...,high,Unclear interest benchmark,Explain floating rate risk and suggest asking ...

In [4]:
df.isna().sum()

id                    0
customer_name         0
contract_type         0
vehicle_type          0
monthly_emi           0
interest_rate         0
tenure_months         0
clause_summary        0
risk_flag             0
issue_type            0
recommended_action    0
dtype: int64

In [7]:
#unique values for important categorical columns
df['contract_type'].value_counts()

contract_type
Car Loan     6
Car Lease    6
Name: count, dtype: int64

In [8]:
df['risk_flag'].value_counts()

risk_flag
high      5
medium    4
low       3
Name: count, dtype: int64

In [9]:
df['monthly_emi'].value_counts()

monthly_emi
18500    2
22000    1
14500    1
21000    1
27500    1
16500    1
19500    1
25500    1
30500    1
13200    1
24500    1
Name: count, dtype: int64

In [10]:
df['vehicle_type'].value_counts()

vehicle_type
Sedan        4
SUV          4
Hatchback    3
EV           1
Name: count, dtype: int64

In [11]:
df['interest_rate'].value_counts()

interest_rate
0.0     6
9.5     1
11.2    1
10.8    1
8.9     1
12.5    1
9.9     1
Name: count, dtype: int64

In [12]:
df['tenure_months'].value_counts()

tenure_months
48    3
36    3
60    1
24    1
72    1
84    1
30    1
42    1
Name: count, dtype: int64

In [14]:
df['clause_summary'].value_counts()

clause_summary
Prepayment allowed only after 24 months with 5% penalty                                 1
Lessee must pay for all maintenance and insurance                                       1
Late payment fee of 3% per month on outstanding amount                                  1
Excess mileage charge of ₹12 per km over 15,000 km per year                             1
Floating interest rate linked to lender's internal benchmark                            1
Early termination fee equal to 6 months of EMI                                          1
No foreclosure charges after 12 months                                                  1
Battery warranty covered only for 24 months or 40,000 km                                1
Mandatory bundled insurance from lender at non-refundable premium                       1
Security deposit of 3 EMIs, refundable at end of lease subject to damage check          1
Processing fee of 1.5% of loan amount, non-refundable                                   1
Lessor can repossess vehicle after 2 consecutive missed payments without court order    1
Name: count, dtype: int64

In [16]:
#Average interest rate per risk level
df.groupby('risk_flag')['interest_rate'].mean()

risk_flag
high      6.900000
low       2.966667
medium    4.850000
Name: interest_rate, dtype: float64

In [9]:
import pandas as pd
df = pd.read_csv('../data/sample_car_contracts.csv')
df.head()

,id,customer_name,contract_type,vehicle_type,monthly_emi,interest_rate,tenure_months,clause_summary,risk_flag,issue_type,recommended_action
0,1,Rahul Mehta,Car Loan,Sedan,18500,9.5,48,Prepayment allowed only after 24 months with 5...,medium,High prepayment charges,Highlight prepayment penalty to user and sugge...
1,2,Anita Rao,Car Lease,SUV,22000,0.0,36,Lessee must pay for all maintenance and insurance,low,Standard maintenance clause,"No action, just explain maintenance responsibi..."
2,3,James Wilson,Car Loan,Hatchback,14500,11.2,60,Late payment fee of 3% per month on outstandin...,high,Aggressive late fee,Flag clause and suggest user request cap on la...
3,4,Meena Iyer,Car Lease,Sedan,21000,0.0,24,"Excess mileage charge of ₹12 per km over 15,00...",medium,High excess mileage rate,Warn user about extra mileage charges and reco...
4,5,Arjun Patel,Car Loan,SUV,27500,10.8,72,Floating interest rate linked to lender's inte...,high,Unclear interest benchmark,Explain floating rate risk and suggest asking ...

In [11]:
df['total_amount'] = df['monthly_emi'] * df['tenure_months']
df[['customer_name', 'monthly_emi', 'tenure_months', 'total_amount']]

   customer_name  monthly_emi  tenure_months  total_amount
0    Rahul Mehta        18500             48        888000
1      Anita Rao        22000             36        792000
2   James Wilson        14500             60        870000
3     Meena Iyer        21000             24        504000
4    Arjun Patel        27500             72       1980000
5      Sana Khan        16500             36        594000
6    Vikram Shah        19500             36        702000
7     Neha Singh        25500             48       1224000
8      David Roy        30500             84       2562000
9    Kiran Kumar        18500             30        555000
10   Pratima Das        13200             48        633600
11     Imran Ali        24500             42       1029000

In [16]:
df['tenure_years'] = df['tenure_months'] / 12
avg_tenure = df.groupby('risk_flag')['tenure_years'].mean()
print(avg_tenure)

risk_flag
high      4.900000
low       2.833333
medium    3.500000
Name: tenure_years, dtype: float64

In [19]:
df["total_amount"] = df["monthly_emi"] * df["tenure_months"]
print("Total Amount Added:")
print(df[["customer_name", "total_amount"]])
print("\n")

df["tenure_years"] = df["tenure_months"] / 12
print("Tenure in Years:")
print(df[["customer_name", "tenure_years"]])
print("\n")

avg_total = df.groupby("risk_flag")["total_amount"].mean()

print("Average Total Contract Amount per Risk Flag:")
print(avg_total)
print("\n")

avg_tenure = df.groupby("risk_flag")["tenure_years"].mean()
print("Average Tenure (Years) per Risk Flag:")
print(avg_tenure)

pd.crosstab(df['risk_flag'], df['recommended_action'])

Total Amount Added:
   customer_name  total_amount
0    Rahul Mehta      42624000
1      Anita Rao      28512000
2   James Wilson      52200000
3     Meena Iyer      12096000
4    Arjun Patel     142560000
5      Sana Khan      21384000
6    Vikram Shah      25272000
7     Neha Singh      58752000
8      David Roy     215208000
9    Kiran Kumar      16650000
10   Pratima Das      30412800
11     Imran Ali      43218000


Tenure in Years:
   customer_name  tenure_years
0    Rahul Mehta           4.0
1      Anita Rao           3.0
2   James Wilson           5.0
3     Meena Iyer           2.0
4    Arjun Patel           6.0
5      Sana Khan           3.0
6    Vikram Shah           3.0
7     Neha Singh           4.0
8      David Roy           7.0
9    Kiran Kumar           2.5
10   Pratima Das           4.0
11     Imran Ali           3.5


Average Total Contract Amount per Risk Flag:
risk_flag
high      94914000.0
low       23478000.0
medium    35971200.0
Name: total_amount, dtype: float64


Average Tenure (Years) per Risk Flag:
risk_flag
high      4.900000
low       2.833333
medium    3.500000
Name: tenure_years, dtype: float64

recommended_action,"Explain condition for refund, low risk",Explain floating rate risk and suggest asking for external benchmark or cap,Flag as risky and suggest negotiating lower termination fee,Flag as unfair tying and suggest independent insurance quote,Flag clause and suggest user request cap on late fee,Highlight cost and suggest user negotiate lower fee,Highlight prepayment penalty to user and suggest negotiation for lower fee,"Mark as positive clause, no action required","No action, just explain maintenance responsibility to user",Strongly warn user and recommend clarification / negotiation,Warn user about battery risk and suggest extended warranty discussion,Warn user about extra mileage charges and recommend realistic mileage estimate
risk_flag,,,,,,,,,,,,
high,0,1,1,1,1,0,0,0,0,1,0,0
low,1,0,0,0,0,0,0,1,1,0,0,0
medium,0,0,0,0,0,1,1,0,0,0,1,1