In [6]:
def extract_sla_details(row):
    """
    Simulates LLM-based SLA extraction.
    Returns SLA details in JSON format.
    """
    return {
    "monthly_emi": row["monthly_emi"],
    "interest_rate": row["interest_rate"],
    "tenure_months": row["tenure_months"],
    "risk_flag": row["risk_flag"],
    "issue_type": row["issue_type"],
    "recommended_action": row["recommended_action"]
}

In [7]:
import pandas as pd

contracts_df = pd.read_csv("../data/sample_car_contracts_with_vin.csv")
contracts_df.head()

,id,customer_name,contract_type,vehicle_type,monthly_emi,interest_rate,tenure_months,clause_summary,risk_flag,issue_type,recommended_action,vin
0,1,Rahul Mehta,Car Loan,Sedan,18500,9.5,48,Prepayment allowed only after 24 months with 5...,medium,High prepayment charges,Highlight prepayment penalty to user and sugge...,1HGCM82633A004352
1,2,Anita Rao,Car Lease,SUV,22000,0.0,36,Lessee must pay for all maintenance and insurance,low,Standard maintenance clause,"No action, just explain maintenance responsibi...",1HGCM82633A004352
2,3,James Wilson,Car Loan,Hatchback,14500,11.2,60,Late payment fee of 3% per month on outstandin...,high,Aggressive late fee,Flag clause and suggest user request cap on la...,1HGCM82633A004352
3,4,Meena Iyer,Car Lease,Sedan,21000,0.0,24,"Excess mileage charge of ₹12 per km over 15,00...",medium,High excess mileage rate,Warn user about extra mileage charges and reco...,1HGCM82633A004352
4,5,Arjun Patel,Car Loan,SUV,27500,10.8,72,Floating interest rate linked to lender's inte...,high,Unclear interest benchmark,Explain floating rate risk and suggest asking ...,1HGCM82633A004352

In [8]:
sla_records = []
for _, row in contracts_df.iterrows():
    sla_records.append({
    "contract_id": row["id"],
    "customer_name": row["customer_name"],
    "sla": extract_sla_details(row)
    })
    
sla_df = pd.DataFrame(sla_records)
sla_df.head()

,contract_id,customer_name,sla
0,1,Rahul Mehta,"{'monthly_emi': 18500, 'interest_rate': 9.5, '..."
1,2,Anita Rao,"{'monthly_emi': 22000, 'interest_rate': 0.0, '..."
2,3,James Wilson,"{'monthly_emi': 14500, 'interest_rate': 11.2, ..."
3,4,Meena Iyer,"{'monthly_emi': 21000, 'interest_rate': 0.0, '..."
4,5,Arjun Patel,"{'monthly_emi': 27500, 'interest_rate': 10.8, ..."

In [9]:
sla_df.to_csv("../data/milestone2_sla_output.csv", index=False)

In [10]:

sla_df.sample(6)

,contract_id,customer_name,sla
7,8,Neha Singh,"{'monthly_emi': 25500, 'interest_rate': 0.0, '..."
1,2,Anita Rao,"{'monthly_emi': 22000, 'interest_rate': 0.0, '..."
0,1,Rahul Mehta,"{'monthly_emi': 18500, 'interest_rate': 9.5, '..."
5,6,Sana Khan,"{'monthly_emi': 16500, 'interest_rate': 0.0, '..."
8,9,David Roy,"{'monthly_emi': 30500, 'interest_rate': 12.5, ..."
9,10,Kiran Kumar,"{'monthly_emi': 18500, 'interest_rate': 0.0, '..."

In [12]:
#import requests
def get_vehicle_details(vin):
    url =f"https://vpic.nhtsa.dot.gov/api/vehicles/DecodeVinValues/{vin}?format=json"
    response = requests.get(url)
    return response.json()["Results"][0]

In [13]:
def extract_vehicle_info(vehicle_raw):
    return {
    "make": vehicle_raw.get("Make"),
    "model": vehicle_raw.get("Model"),
    "year": vehicle_raw.get("ModelYear")
    }

In [14]:
def enrich_contract_with_vehicle(row):
    vehicle_raw = get_vehicle_details(row["vin"])
    vehicle_info = extract_vehicle_info(vehicle_raw)
    return {
        "contract_id": row["id"],
        "customer_name": row["customer_name"],
        "contract_type": row["contract_type"],
        "sla": extract_sla_details(row),
        "vehicle": vehicle_info
        }

In [18]:
combined_records = []
for _, row in contracts_df.iterrows():
    combined_records.append(enrich_contract_with_vehicle(row))
combined_df = pd.DataFrame(combined_records)
combined_df.head()

NameError: name 'requests' is not defined

In [17]:
combined_df.to_csv("../data/milestone2_evaluation_output.csv", index=False)

NameError: name 'combined_df' is not defined