In [2]:
import pandas as pd

# Load & Explore Contract Data
df=pd.read_csv('../data/batch2_contracts_125rows.csv')
df.head()

,contract_id,raw_text,apr,term_months,monthly_payment,penalty_clause,recommended_action,risk_flag
0,1,This contract between Prime Auto and Emily Sto...,10.49,24,959,NaN,Approve,Low
1,2,This contract between ABC Motors and Priya Sha...,3.78,24,804,Early termination fee $300,Approve,Low
2,3,This contract between DriveEasy Finance and Sa...,5.41,24,774,Late fee $50,Reject,High
3,4,This contract between National Motors and Alex...,5.26,48,1028,Late fee $25,Approve,High
4,5,This contract between National Motors and John...,5.97,36,1180,NaN,Approve,Low

In [3]:
# Create duplicate columns holding expected values for comparison
df["expected_apr"] = df["apr"]
df["expected_term"] = df["term_months"]
df["expected_payment"] = df["monthly_payment"]
df["expected_penalty"] = df["penalty_clause"]

In [ ]:
# Display all column names in the dataframe
df.columns

Index(['contract_id', 'raw_text', 'apr', 'term_months', 'monthly_payment',
       'penalty_clause', 'recommended_action', 'risk_flag', 'expected_apr',
       'expected_term', 'expected_payment', 'expected_penalty'],
      dtype='object')

In [5]:
# Display penalty vs expected penalty to verify
df[['penalty_clause',"expected_penalty"]]

                 penalty_clause            expected_penalty
0                           NaN                         NaN
1    Early termination fee $300  Early termination fee $300
2                  Late fee $50                Late fee $50
3                  Late fee $25                Late fee $25
4                           NaN                         NaN
..                          ...                         ...
120                Late fee $25                Late fee $25
121                Late fee $25                Late fee $25
122  Early termination fee $300  Early termination fee $300
123                         NaN                         NaN
124                Late fee $50                Late fee $50

[125 rows x 2 columns]

In [6]:
# APR score: 1 if actual == expected else 0
df["apr_score"] = (df["apr"]==df["expected_apr"]).astype(int)

# Term score: 1 if actual == expected else 0
df["term_score"] = (df["term_months"]==df["expected_term"]).astype(int)

# Payment score: 1 if actual == expected else 0
df["payment_score"] = (df["monthly_payment"]==df["expected_payment"]).astype(int)

# Penalty score: 1 if actual == expected else 0
df["penalty_score"] = (df["penalty_clause"] == df["expected_penalty"]).astype(int)

# Total score is sum of all individual scores
df["total_score"] = (df["apr_score"] + df["term_score"] + df["payment_score"] + df["penalty_score"])

In [ ]:
df["quality_score"] = (df["total_score"]/3) * 100

In [ ]:
df[["apr_score" ,"term_score","payment_score","penalty_score","total_score","quality_score"]].head(20)

,apr_score,term_score,payment_score,penalty_score,total_score,quality_score
0,1,1,1,0,3,100.000000
1,1,1,1,1,4,133.333333
2,1,1,1,1,4,133.333333
3,1,1,1,1,4,133.333333
4,1,1,1,0,3,100.000000
5,1,1,1,0,3,100.000000
6,1,1,1,0,3,100.000000
7,1,1,1,1,4,133.333333
8,1,1,1,0,3,100.000000
9,1,1,1,1,4,133.333333
10,1,1,1,1,4,133.333333
11,1,1,1,0,3,100.000000
12,1,1,1,1,4,133.333333
13,1,1,1,1,4,133.333333
14,1,1,1,1,4,133.333333
15,1,1,1,1,4,133.333333
16,1,1,1,1,4,133.333333
17,1,1,1,1,4,133.333333
18,1,1,1,1,4,133.333333
19,1,1,1,0,3,100.000000

In [ ]:
# Import requests library for making API calls to vehicle database
import requests

In [ ]:
def get_vehicle_details(vin):
    pass

In [ ]:
#  Vehicle API Lookup

import requests

def get_vehicle_details(vin):
    # Call NHTSA API with VIN to get vehicle information
    url = f"https://vpic.nhtsa.dot.gov/api/vehicles/DecodeVinValues/{vin}?format=json"
    response = requests.get(url)
    data = response.json()
    # Return the first result which contains all vehicle details
    return data["Results"][0]

In [ ]:
# Test the function with a sample VIN
veichle = get_vehicle_details("1FTEW1EF3GKE12345")
veichle

{'ABS': '',
 'ActiveSafetySysNote': '',
 'AdaptiveCruiseControl': '',
 'AdaptiveDrivingBeam': '',
 'AdaptiveHeadlights': '',
 'AdditionalErrorText': 'The Model Year decoded for this VIN may be incorrect. If you know the Model year, please enter it and decode again to get more accurate information.',
 'AirBagLocCurtain': '',
 'AirBagLocFront': '1st Row (Driver and Passenger)',
 'AirBagLocKnee': '',
 'AirBagLocSeatCushion': '',
 'AirBagLocSide': '1st and 2nd Rows',
 'AutoReverseSystem': '',
 'AutomaticPedestrianAlertingSound': '',
 'AxleConfiguration': '',
 'Axles': '',
 'BasePrice': '',
 'BatteryA': '',
 'BatteryA_to': '',
 'BatteryCells': '',
 'BatteryInfo': '',
 'BatteryKWh': '',
 'BatteryKWh_to': '',
 'BatteryModules': '',
 'BatteryPacks': '',
 'BatteryType': '',
 'BatteryV': '',
 'BatteryV_to': '',
 'BedLengthIN': '',
 'BedType': '',
 'BlindSpotIntervention': '',
 'BlindSpotMon': '',
 'BodyCabType': 'Crew/Super Crew/Crew Max',
 'BodyClass': 'Pickup',
 'BrakeSystemDesc': '',
 'BrakeSystemType': 'Hydraulic',
 'BusFloorConfigType': 'Not Applicable',
 'BusLength': '',
 'BusType': 'Not Applicable',
 'CAN_AACN': '',
 'CIB': '',
 'CashForClunkers': '',
 'ChargerLevel': '',
 'ChargerPowerKW': '',
 'CombinedBrakingSystem': '',
 'CoolingType': '',
 'CurbWeightLB': '',
 'CustomMotorcycleType': 'Not Applicable',
 'DaytimeRunningLight': '',
 'DestinationMarket': '',
 'DisplacementCC': '5000.0',
 'DisplacementCI': '305.11872047366',
 'DisplacementL': '5.0',
 'Doors': '',
 'DriveType': '4WD/4-Wheel Drive/4x4',
 'DriverAssist': '',
 'DynamicBrakeSupport': '',
 'EDR': '',
 'ESC': '',
 'EVDriveUnit': '',
 'ElectrificationLevel': '',
 'EngineConfiguration': 'V-Shaped',
 'EngineCycles': '',
 'EngineCylinders': '8',
 'EngineHP': '386',
 'EngineHP_to': '',
 'EngineKW': '',
 'EngineManufacturer': 'Ford',
 'EngineModel': '',
 'EntertainmentSystem': '',
 'ErrorCode': '1',
 'ErrorText': '1 - Check Digit (9th position) does not calculate properly',
 'ForwardCollisionWarning': '',
 'FuelInjectionType': '',
 'FuelTankMaterial': '',
 'FuelTankType': '',
 'FuelTypePrimary': 'Gasoline',
 'FuelTypeSecondary': '',
 'GCWR': '',
 'GCWR_to': '',
 'GVWR': 'Class 2E: 6,001 - 7,000 lb (2,722 - 3,175 kg)',
 'GVWR_to': '',
 'KeylessIgnition': '',
 'LaneCenteringAssistance': '',
 'LaneDepartureWarning': '',
 'LaneKeepSystem': '',
 'LowerBeamHeadlampLightSource': '',
 'Make': 'FORD',
 'MakeID': '460',
 'Manufacturer': 'FORD MOTOR COMPANY',
 'ManufacturerId': '976',
 'Model': 'F-150',
 'ModelID': '1801',
 'ModelYear': '2016',
 'MotorcycleChassisType': 'Not Applicable',
 'MotorcycleSuspensionType': 'Not Applicable',
 'NCSABodyType': '',
 'NCSAMake': '',
 'NCSAMapExcApprovedBy': '',
 'NCSAMapExcApprovedOn': '',
 'NCSAMappingException': '',
 'NCSAModel': '',
 'NCSANote': '',
 'NonLandUse': '',
 'Note': '',
 'OtherBusInfo': '',
 'OtherEngineInfo': '4V',
 'OtherMotorcycleInfo': '',
 'OtherRestraintSystemInfo': '',
 'OtherTrailerInfo': '',
 'ParkAssist': '',
 'PedestrianAutomaticEmergencyBraking': '',
 'PlantCity': 'KANSAS CITY',
 'PlantCompanyName': 'Kansas City',
 'PlantCountry': 'UNITED STATES (USA)',
 'PlantState': 'MISSOURI',
 'PossibleValues': '',
 'Pretensioner': '',
 'RearAutomaticEmergencyBraking': '',
 'RearCrossTrafficAlert': '',
 'RearVisibilitySystem': '',
 'SAEAutomationLevel': '',
 'SAEAutomationLevel_to': '',
 'SeatBeltsAll': 'Manual',
 'SeatRows': '',
 'Seats': '',
 'SemiautomaticHeadlampBeamSwitching': '',
 'Series': '',
 'Series2': '',
 'SteeringLocation': '',
 'SuggestedVIN': '',
 'TPMS': 'Direct',
 'TopSpeedMPH': '',
 'TrackWidth': '',
 'TractionControl': '',
 'TrailerBodyType': 'Not Applicable',
 'TrailerLength': '',
 'TrailerType': 'Not Applicable',
 'TransmissionSpeeds': '',
 'TransmissionStyle': '',
 'Trim': '',
 'Trim2': '',
 'Turbo': '',
 'VIN': '1FTEW1EF3GKE12345',
 'ValveTrainDesign': '',
 'VehicleDescriptor': '1FTEW1EF*GK',
 'VehicleType': 'TRUCK',
 'WheelBaseLong': '',
 'WheelBaseShort': '',
 'WheelBaseType': '',
 'WheelSizeFront': '',
 'WheelSizeRear': '',
 'WheelieMitigation': '',
 'Wheels': '',
 'Windows': ''}

In [ ]:
#  Extract Only Key Vehicle Info from API response
# Filter out unnecessary data and keep only make, model, year, and body type
important_veichle_info = {
    "make":veichle.get("Make"),
    "model":veichle.get("Model"),
    "year":veichle.get("ModelYear"),
    "body_type":veichle.get("BodyClass")
}
important_veichle_info

{'make': 'FORD', 'model': 'F-150', 'year': '2016', 'body_type': 'Pickup'}

In [ ]:
veichle_year = int(important_veichle_info["year"])
if veichle_year < 2015:
    risk_level = "High"
else:
    risk_level = "Normal"

In [ ]:
# Determine Risk Level by Year
# Create cleaned vehicle data dictionary with key vehicle information
cleaned_veichle_data = {
    "make":veichle.get("Make"),
    "model":veichle.get("Model"),
    "year":veichle.get("ModelYear"),
    "body_type":veichle.get("BodyClass")
}
cleaned_veichle_data

{'make': 'FORD', 'model': 'F-150', 'year': '2016', 'body_type': 'Pickup'}

In [ ]:
# Load contract data with VIN information from CSV file
contracts_df = pd.read_csv('../data/sample_car_contracts.csv')
df.head()

,contract_id,raw_text,apr,term_months,monthly_payment,penalty_clause,recommended_action,risk_flag,expected_apr,expected_term,expected_payment,expected_penalty,apr_score,term_score,payment_score,penalty_score,total_score,quality_score
0,1,This contract between Prime Auto and Emily Sto...,10.49,24,959,NaN,Approve,Low,10.49,24,959,NaN,1,1,1,0,3,100.000000
1,2,This contract between ABC Motors and Priya Sha...,3.78,24,804,Early termination fee $300,Approve,Low,3.78,24,804,Early termination fee $300,1,1,1,1,4,133.333333
2,3,This contract between DriveEasy Finance and Sa...,5.41,24,774,Late fee $50,Reject,High,5.41,24,774,Late fee $50,1,1,1,1,4,133.333333
3,4,This contract between National Motors and Alex...,5.26,48,1028,Late fee $25,Approve,High,5.26,48,1028,Late fee $25,1,1,1,1,4,133.333333
4,5,This contract between National Motors and John...,5.97,36,1180,NaN,Approve,Low,5.97,36,1180,NaN,1,1,1,0,3,100.000000

In [ ]:
# Function to enrich contract data with vehicle information from API
# Takes a contract row and retrieves vehicle details using the VIN
def enrich_contract_with_veichle(contract_row):
    vin = contract_row["vin"]
    # Fetch vehicle details from NHTSA API
    veichle = get_vehicle_details(vin)

    # Return enriched contract with vehicle information
    return{
        "contract_id" : contract_row["contract_id"],
        "customer_name" : contract_row["customer_name"],
        "vin" : vin,
        "veichle" : {
            "make":veichle.get("Make"),
    "model":veichle.get("Model"),
    "year":veichle.get("ModelYear"),
    }
    }

In [ ]:
# Loop through all contracts and enrich each with vehicle data
# This combines contract information with vehicle details from the API
combine_records = []

for _, row in contracts_df.iterows():
    # Append enriched contract data to the list
    combine_records.append(enrich_contract_with_veichle(row))