In [1]:
import pandas as pd
df = pd.read_csv("milestone1_sriharini.csv")

In [2]:
import numpy as np

In [3]:
df.head()

,Unnamed: 0,contract_id,raw_text,apr,term_months,monthly_payment,penalty_clause,recommended_action,risk_flag
0,0,1,This contract between Prime Auto and Emily Sto...,10.49,24,959,NaN,Approve,Low
1,1,2,This contract between ABC Motors and Priya Sha...,3.78,24,804,Early termination fee $300,Approve,Low
2,2,3,This contract between DriveEasy Finance and Sa...,5.41,24,774,Late fee $50,Reject,High
3,3,4,This contract between National Motors and Alex...,5.26,48,1028,Late fee $25,Approve,High
4,4,5,This contract between National Motors and John...,5.97,36,1180,NaN,Approve,Low

In [4]:
df.columns

Index(['Unnamed: 0', 'contract_id', 'raw_text', 'apr', 'term_months',
       'monthly_payment', 'penalty_clause', 'recommended_action', 'risk_flag'],
      dtype='object')

In [5]:
df = df.rename(columns={"penalty": "penalty_clause"})

In [6]:
df["expected_apr"] = df["apr"]
df["expected_term"] = df["term_months"]
df["expeted_payment"] = df["monthly_payment"]
df["expected_penalty"] = df["penalty_clause"]

In [7]:
df[["penalty_clause","expected_penalty"]].head()

               penalty_clause            expected_penalty
0                         NaN                         NaN
1  Early termination fee $300  Early termination fee $300
2                Late fee $50                Late fee $50
3                Late fee $25                Late fee $25
4                         NaN                         NaN

In [8]:
# if extracted APR exactly matches expected
# APR score 1
# if not score 0

# if extracted term months equals expected
# term months score 1
# else score 0

# if extracted penalty text matches expected
# penalty score 1
# else score 0

df["apr_score"] = (df["apr"] == df["expected_apr"]).astype(int)

In [9]:
df["term_score"] = (df["term_months"] == df["expected_term"]).astype(int)

In [10]:
df["penalty_score"] = (df["penalty_clause"] == df["expected_penalty"]).astype(int)

In [11]:
df["total_score"] = (df["apr_score"] + df["term_score"] + df["penalty_score"])

In [12]:
df["quality_percent"] = (df["total_score"]/3)*100
df[["apr_score","term_score","penalty_score","total_score","quality_percent"]].head()

   apr_score  term_score  penalty_score  total_score  quality_percent
0          1           1              0            2        66.666667
1          1           1              1            3       100.000000
2          1           1              1            3       100.000000
3          1           1              1            3       100.000000
4          1           1              0            2        66.666667

In [37]:
def extract_sla_details(row):
    """
    Simulates LLM-based SLA extraction using expected fields.
    """
    return {
        "monthly_emi": row["expected_payment"],
        "interest_rate": row["expected_apr"],
        "tenure_months": row["expected_term"],
        "risk_flag": "Low" if row["expected_penalty"] == "" else "High",
        "issue_type": "Penalty Clause" if row["expected_penalty"] != "" else "None",
        "recommended_action": "Review Contract" if row["expected_penalty"] != "" else "Approve"
    }

In [25]:
import pandas as pd
contracts_df = pd.read_csv(
    r"E:\infosys\infosys-carlease-contract-ai-group2\data\contract_evaluation_dataset_sri.csv"
)
contracts_df.head()

,contract_id,raw_text,expected_apr,expected_term,expected_payment,expected_penalty
0,1,This contract between Prime Auto and Emily Sto...,10.49,24,959,NaN
1,2,This contract between ABC Motors and Priya Sha...,3.78,24,804,Early termination fee $300
2,3,This contract between DriveEasy Finance and Sa...,5.41,24,774,Late fee $50
3,4,This contract between National Motors and Alex...,5.26,48,1028,Late fee $25
4,5,This contract between National Motors and John...,5.97,36,1180,NaN

In [32]:
contracts_df = contracts_df.rename(columns={"Unnamed: 0": "contract_id"})
print(contracts_df.columns.tolist())

contracts_df["id"] = contracts_df.index + 1

['contract_id', 'raw_text', 'expected_apr', 'expected_term', 'expected_payment', 'expected_penalty']

In [36]:
print(contracts_df.columns.tolist())

['contract_id', 'raw_text', 'expected_apr', 'expected_term', 'expected_payment', 'expected_penalty', 'id']

In [39]:
sla_records = []

for _, row in contracts_df.iterrows():
    sla_records.append({
        "contract_id": row["contract_id"],
        "sla": extract_sla_details(row)
    })

sla_df = pd.DataFrame(sla_records)
sla_df.head()

   contract_id                                                sla
0            1  {'monthly_emi': 959, 'interest_rate': 10.49, '...
1            2  {'monthly_emi': 804, 'interest_rate': 3.78, 't...
2            3  {'monthly_emi': 774, 'interest_rate': 5.41, 't...
3            4  {'monthly_emi': 1028, 'interest_rate': 5.26, '...
4            5  {'monthly_emi': 1180, 'interest_rate': 5.97, '...

In [40]:
sla_df.to_csv("../data/milestone2_sla_output.csv", index=False)

In [41]:
sla_df.sample(5)

    contract_id                                                sla
15           16  {'monthly_emi': 810, 'interest_rate': 10.34, '...
7             8  {'monthly_emi': 246, 'interest_rate': 4.9, 'te...
20           21  {'monthly_emi': 219, 'interest_rate': 9.99, 't...
12           13  {'monthly_emi': 605, 'interest_rate': 6.43, 't...
4             5  {'monthly_emi': 1180, 'interest_rate': 5.97, '...

In [4]:
import pandas as pd

df = pd.read_csv("milestone1_sriharini.csv")  
df.to_csv("milestone2_evaluationsriharini_output.csv", index=False)

In [1]:
import requests

In [2]:
def get_vehicle_details(vin):
    pass

In [2]:
import requests
def get_vehicle_details(vin):
    url = f"https://vpic.nhtsa.dot.gov/api/vehicles/DecodevinValues/{vin}?format=json"
    response = requests.get (url)
    data = response.json()
    return data ["Results"][0]

In [15]:
vehicle = get_vehicle_details("5YJ3E1EA7HF000337")
vehicle

{'ABS': 'Standard',
 'ActiveSafetySysNote': '',
 'AdaptiveCruiseControl': 'Optional',
 'AdaptiveDrivingBeam': '',
 'AdaptiveHeadlights': '',
 'AdditionalErrorText': '',
 'AirBagLocCurtain': '',
 'AirBagLocFront': '1st Row (Driver and Passenger)',
 'AirBagLocKnee': '1st Row (Driver and Passenger)',
 'AirBagLocSeatCushion': '',
 'AirBagLocSide': '1st Row (Driver and Passenger)',
 'AutoReverseSystem': 'Standard',
 'AutomaticPedestrianAlertingSound': 'Standard',
 'AxleConfiguration': '',
 'Axles': '2',
 'BasePrice': '68000.00',
 'BatteryA': '',
 'BatteryA_to': '',
 'BatteryCells': '',
 'BatteryInfo': '',
 'BatteryKWh': '',
 'BatteryKWh_to': '',
 'BatteryModules': '',
 'BatteryPacks': '',
 'BatteryType': '',
 'BatteryV': '',
 'BatteryV_to': '',
 'BedLengthIN': '',
 'BedType': 'Not Applicable',
 'BlindSpotIntervention': '',
 'BlindSpotMon': 'Standard',
 'BodyCabType': 'Not Applicable',
 'BodyClass': 'Sedan/Saloon',
 'BrakeSystemDesc': '',
 'BrakeSystemType': '',
 'BusFloorConfigType': 'Not Applicable',
 'BusLength': '',
 'BusType': 'Not Applicable',
 'CAN_AACN': '',
 'CIB': 'Standard',
 'CashForClunkers': '',
 'ChargerLevel': '',
 'ChargerPowerKW': '',
 'CombinedBrakingSystem': '',
 'CoolingType': '',
 'CurbWeightLB': '',
 'CustomMotorcycleType': 'Not Applicable',
 'DaytimeRunningLight': 'Standard',
 'DestinationMarket': '',
 'DisplacementCC': '',
 'DisplacementCI': '',
 'DisplacementL': '',
 'Doors': '4',
 'DriveType': '',
 'DriverAssist': '',
 'DynamicBrakeSupport': 'Standard',
 'EDR': '',
 'ESC': 'Standard',
 'EVDriveUnit': '',
 'ElectrificationLevel': 'BEV (Battery Electric Vehicle)',
 'EngineConfiguration': '',
 'EngineCycles': '',
 'EngineCylinders': '',
 'EngineHP': '',
 'EngineHP_to': '',
 'EngineKW': '',
 'EngineManufacturer': '',
 'EngineModel': '',
 'EntertainmentSystem': '',
 'ErrorCode': '0',
 'ErrorText': '0 - VIN decoded clean. Check Digit (9th position) is correct',
 'ForwardCollisionWarning': 'Standard',
 'FuelInjectionType': '',
 'FuelTankMaterial': '',
 'FuelTankType': '',
 'FuelTypePrimary': 'Electric',
 'FuelTypeSecondary': '',
 'GCWR': '',
 'GCWR_to': '',
 'GVWR': 'Class 1: 6,000 lb or less (2,722 kg or less)',
 'GVWR_to': 'Class 1: 6,000 lb or less (2,722 kg or less)',
 'KeylessIgnition': 'Standard',
 'LaneCenteringAssistance': '',
 'LaneDepartureWarning': 'Standard',
 'LaneKeepSystem': 'Optional',
 'LowerBeamHeadlampLightSource': '',
 'Make': 'TESLA',
 'MakeID': '441',
 'Manufacturer': 'TESLA, INC.',
 'ManufacturerId': '955',
 'Model': 'Model 3',
 'ModelID': '17834',
 'ModelYear': '2017',
 'MotorcycleChassisType': 'Not Applicable',
 'MotorcycleSuspensionType': 'Not Applicable',
 'NCSABodyType': '',
 'NCSAMake': '',
 'NCSAMapExcApprovedBy': '',
 'NCSAMapExcApprovedOn': '',
 'NCSAMappingException': '',
 'NCSAModel': '',
 'NCSANote': '',
 'NonLandUse': '',
 'Note': '',
 'OtherBusInfo': '',
 'OtherEngineInfo': 'Single Motor - Standard',
 'OtherMotorcycleInfo': '',
 'OtherRestraintSystemInfo': 'Type 2 manual seatbelts (FR, SR*3), PODS',
 'OtherTrailerInfo': '',
 'ParkAssist': '',
 'PedestrianAutomaticEmergencyBraking': 'Optional',
 'PlantCity': 'FREMONT',
 'PlantCompanyName': '',
 'PlantCountry': 'UNITED STATES (USA)',
 'PlantState': 'CALIFORNIA',
 'PossibleValues': '',
 'Pretensioner': '',
 'RearAutomaticEmergencyBraking': '',
 'RearCrossTrafficAlert': '',
 'RearVisibilitySystem': 'Standard',
 'SAEAutomationLevel': '1',
 'SAEAutomationLevel_to': '',
 'SeatBeltsAll': 'Manual',
 'SeatRows': '2',
 'Seats': '5',
 'SemiautomaticHeadlampBeamSwitching': 'Standard',
 'Series': '',
 'Series2': '',
 'SteeringLocation': 'Left-Hand Drive (LHD)',
 'SuggestedVIN': '',
 'TPMS': '',
 'TopSpeedMPH': '',
 'TrackWidth': '',
 'TractionControl': 'Standard',
 'TrailerBodyType': 'Not Applicable',
 'TrailerLength': '',
 'TrailerType': 'Not Applicable',
 'TransmissionSpeeds': '',
 'TransmissionStyle': '',
 'Trim': '',
 'Trim2': '',
 'Turbo': '',
 'VIN': '5YJ3E1EA7HF000337',
 'ValveTrainDesign': '',
 'VehicleDescriptor': '5YJ3E1EA*HF',
 'VehicleType': 'PASSENGER CAR',
 'WheelBaseLong': '',
 'WheelBaseShort': '116.50',
 'WheelBaseType': '',
 'WheelSizeFront': '',
 'WheelSizeRear': '',
 'WheelieMitigation': '',
 'Wheels': '4',
 'Windows': ''}

In [16]:
important_vehicle_info = {
    "make":vehicle.get("Make"),
    "model":vehicle.get("Model"),
    "year":vehicle.get("ModelYear"),
    "body_type":vehicle.get("BodyClass")
 }
important_vehicle_info

{'make': 'TESLA',
 'model': 'Model 3',
 'year': '2017',
 'body_type': 'Sedan/Saloon'}

In [17]:
vehicle_year = int(important_vehicle_info["year"])

if vehicle_year < 2015:
    risk_level = "HIGH"

else:
    risk_level = "NORMAL"

risk_level

'NORMAL'

In [18]:
clean_vehicle_info = {
    "make":vehicle.get("Make"),
    "model":vehicle.get("Model"),
    "year":vehicle.get("ModelYear"),
    "body_type":vehicle.get("BodyClass")
 }
clean_vehicle_info

{'make': 'TESLA',
 'model': 'Model 3',
 'year': '2017',
 'body_type': 'Sedan/Saloon'}

In [1]:
import pandas as pd
contracts_df = pd.read_csv(
    r"E:\infosys\infosys-carlease-contract-ai-group2\data\contract_evaluation_dataset_sri.csv"
)
contracts_df.head()

,contract_id,raw_text,expected_apr,expected_term,expected_payment,expected_penalty
0,1,This contract between Prime Auto and Emily Sto...,10.49,24,959,NaN
1,2,This contract between ABC Motors and Priya Sha...,3.78,24,804,Early termination fee $300
2,3,This contract between DriveEasy Finance and Sa...,5.41,24,774,Late fee $50
3,4,This contract between National Motors and Alex...,5.26,48,1028,Late fee $25
4,5,This contract between National Motors and John...,5.97,36,1180,NaN

In [2]:
contracts_df["vin"] = "5YJ3E1EA7HF000337"

In [3]:
print(contracts_df.columns.tolist())

['contract_id', 'raw_text', 'expected_apr', 'expected_term', 'expected_payment', 'expected_penalty', 'vin']

In [8]:
def get_vehicle_details(vin):
    ...

def extract_vehicle_info(vehicle_raw):
    ...

def extract_sla_details(row):
    ...

def enrich_contract_with_vehicle(row):
    vehicle_raw = get_vehicle_details(row["vin"])
    vehicle_info = extract_vehicle_info(vehicle_raw)
    return {
        "contract_id": row["contract_id"],
        "sla": extract_sla_details(row),
        "vehicle": vehicle_info
    }

In [11]:
import requests

def get_vehicle_details(vin):
    try:
        url = f"https://vpic.nhtsa.dot.gov/api/vehicles/DecodeVinValues/{vin}?format=json"
        response = requests.get(url, timeout=10)

        if response.status_code != 200:
            return None

        data = response.json()
        results = data.get("Results")

        if not results:
            return None

        return results[0]

    except Exception as e:
        return None

In [12]:
def extract_vehicle_info(vehicle_raw):
    if vehicle_raw is None:
        return {
            "make": None,
            "model": None,
            "year": None
        }

    return {
        "make": vehicle_raw.get("Make"),
        "model": vehicle_raw.get("Model"),
        "year": vehicle_raw.get("ModelYear")
    }

In [13]:
def enrich_contract_with_vehicle(row):
    vehicle_raw = get_vehicle_details(row["vin"])
    vehicle_info = extract_vehicle_info(vehicle_raw)

    return {
        "contract_id": row["contract_id"],
        "sla": extract_sla_details(row),
        "vehicle": vehicle_info
    }

In [14]:
combined_records = []

for _, row in contracts_df.iterrows():
    combined_records.append(enrich_contract_with_vehicle(row))

combined_df = pd.DataFrame(combined_records)
combined_df.head()

   contract_id   sla                                            vehicle
0            1  None  {'make': 'TESLA', 'model': 'Model 3', 'year': ...
1            2  None  {'make': 'TESLA', 'model': 'Model 3', 'year': ...
2            3  None  {'make': 'TESLA', 'model': 'Model 3', 'year': ...
3            4  None  {'make': 'TESLA', 'model': 'Model 3', 'year': ...
4            5  None  {'make': 'TESLA', 'model': 'Model 3', 'year': ...

In [15]:
combined_df.to_csv("../data/milestone2_evaluation_output.csv", index=False)