In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../data/milestone1_output_suresh.csv")
df.head()

,contract_id,extracted_text,apr,term_months,monthly_payment,penalty
0,1,This contract between Prime Auto and Emily Sto...,10.49,24,959,none
1,2,This contract between ABC Motors and Priya Sha...,3.78,24,804,early termination fee $300
2,3,This contract between DriveEasy Finance and Sa...,5.41,24,774,late fee $50
3,4,This contract between National Motors and Alex...,5.26,48,1028,late fee $25
4,5,This contract between National Motors and John...,5.97,36,1180,none

In [4]:
# Ground Truth Simulation

df["expected_apr"] = df["apr"]
df["expected_term"] = df["term_months"]
df["expeted_payment"] = df["monthly_payment"]
df["expected_penalty"] = df["penalty_clause"]

KeyError: 'penalty_clause'

In [5]:
df.columns

Index(['contract_id', 'extracted_text', 'apr', 'term_months',
       'monthly_payment', 'penalty', 'expected_apr', 'expected_term',
       'expeted_payment'],
      dtype='object')

In [6]:
df = df.rename(columns={"penalty": "penalty_clause"})

In [7]:
df.columns

Index(['contract_id', 'extracted_text', 'apr', 'term_months',
       'monthly_payment', 'penalty_clause', 'expected_apr', 'expected_term',
       'expeted_payment'],
      dtype='object')

In [9]:
df["expected_apr"] = df["apr"]
df["expected_term"] = df["term_months"]
df["expeted_payment"] = df["monthly_payment"]
df["expected_penalty"] = df["penalty_clause"]

In [10]:
df[["penalty_clause","expected_penalty"]].head()

               penalty_clause            expected_penalty
0                        none                        none
1  early termination fee $300  early termination fee $300
2                late fee $50                late fee $50
3                late fee $25                late fee $25
4                        none                        none

In [21]:
# if extracted APR exactly matches expected
# APR score 1
# if not score 0

# if extracted term months equals expected
# term months score 1
# else score 0

# if extracted penalty text matches expected
# penalty score 1
# else score 0

df["apr_score"] = (df["apr"] == df["expected_apr"]).astype(int)


df["term_score"] = (df["term_months"] == df["expected_term"]).astype(int)
df["penalty_score"] = (df["penalty_clause"] == df["expected_penalty"]).astype(int)

df["total_score"] = (df["apr_score"] + df["term_score"] + df["payment_score"] + df["penalty_score"])

KeyError: 'payment_score'

In [22]:
df["apr_score"] = (df["apr"] == df["expected_apr"]).astype(int)

In [23]:
df["term_score"] = (df["term_months"] == df["expected_term"]).astype(int)

In [24]:
df["penalty_score"] = (df["penalty_clause"] == df["expected_penalty"]).astype(int)

In [26]:
df["total_score"] = (df["apr_score"] + df["term_score"] + df["penalty_score"])

In [27]:
df["quality_percent"] = (df["total_score"]/3)*100

In [28]:
df[["apr_score","term_score","penalty_score","total_score","quality_percent"]].head()

   apr_score  term_score  penalty_score  total_score  quality_percent
0          1           1              1            3            100.0
1          1           1              1            3            100.0
2          1           1              1            3            100.0
3          1           1              1            3            100.0
4          1           1              1            3            100.0

In [31]:
df.to_csv("../data/milestone2_evaluation_output.csv",index=False)

In [1]:
import requests

In [3]:
def get_vehicle_details(vin):
    pass

In [ ]:
# API Call code

import requests

def get_vehicle_details(vin):
    url = f"https://vpic.nhtsa.dot.gov/api/vehicles/DecodeVinValues/{vin}?format=json"
    response = requests.get(url)
    data = response.json()
    return data["Results"][0]

In [2]:
vehicle = get_vehicle_details("1HGCM82633A004352")
vehicle

{'ABS': '',
 'ActiveSafetySysNote': '',
 'AdaptiveCruiseControl': '',
 'AdaptiveDrivingBeam': '',
 'AdaptiveHeadlights': '',
 'AdditionalErrorText': '',
 'AirBagLocCurtain': '1st and 2nd Rows',
 'AirBagLocFront': '1st Row (Driver and Passenger)',
 'AirBagLocKnee': '',
 'AirBagLocSeatCushion': '',
 'AirBagLocSide': '1st Row (Driver and Passenger)',
 'AutoReverseSystem': '',
 'AutomaticPedestrianAlertingSound': '',
 'AxleConfiguration': '',
 'Axles': '',
 'BasePrice': '',
 'BatteryA': '',
 'BatteryA_to': '',
 'BatteryCells': '',
 'BatteryInfo': '',
 'BatteryKWh': '',
 'BatteryKWh_to': '',
 'BatteryModules': '',
 'BatteryPacks': '',
 'BatteryType': '',
 'BatteryV': '',
 'BatteryV_to': '',
 'BedLengthIN': '',
 'BedType': 'Not Applicable',
 'BlindSpotIntervention': '',
 'BlindSpotMon': '',
 'BodyCabType': 'Not Applicable',
 'BodyClass': 'Coupe',
 'BrakeSystemDesc': '',
 'BrakeSystemType': '',
 'BusFloorConfigType': 'Not Applicable',
 'BusLength': '',
 'BusType': 'Not Applicable',
 'CAN_AACN': '',
 'CIB': '',
 'CashForClunkers': '',
 'ChargerLevel': '',
 'ChargerPowerKW': '',
 'CombinedBrakingSystem': '',
 'CoolingType': '',
 'CurbWeightLB': '',
 'CustomMotorcycleType': 'Not Applicable',
 'DaytimeRunningLight': '',
 'DestinationMarket': '',
 'DisplacementCC': '2998.832712',
 'DisplacementCI': '183',
 'DisplacementL': '2.998832712',
 'Doors': '2',
 'DriveType': '',
 'DriverAssist': '',
 'DynamicBrakeSupport': '',
 'EDR': '',
 'ESC': '',
 'EVDriveUnit': '',
 'ElectrificationLevel': '',
 'EngineConfiguration': 'V-Shaped',
 'EngineCycles': '',
 'EngineCylinders': '6',
 'EngineHP': '240',
 'EngineHP_to': '',
 'EngineKW': '',
 'EngineManufacturer': '',
 'EngineModel': 'J30A4',
 'EntertainmentSystem': '',
 'ErrorCode': '0',
 'ErrorText': '0 - VIN decoded clean. Check Digit (9th position) is correct',
 'ForwardCollisionWarning': '',
 'FuelInjectionType': '',
 'FuelTankMaterial': '',
 'FuelTankType': '',
 'FuelTypePrimary': 'Gasoline',
 'FuelTypeSecondary': '',
 'GCWR': '',
 'GCWR_to': '',
 'GVWR': 'Class 1C: 4,001 - 5,000 lb (1,814 - 2,268 kg)',
 'GVWR_to': 'Class 1: 6,000 lb or less (2,722 kg or less)',
 'KeylessIgnition': '',
 'LaneCenteringAssistance': '',
 'LaneDepartureWarning': '',
 'LaneKeepSystem': '',
 'LowerBeamHeadlampLightSource': '',
 'Make': 'HONDA',
 'MakeID': '474',
 'Manufacturer': 'AMERICAN HONDA MOTOR CO., INC.',
 'ManufacturerId': '988',
 'Model': 'Accord',
 'ModelID': '1861',
 'ModelYear': '2003',
 'MotorcycleChassisType': 'Not Applicable',
 'MotorcycleSuspensionType': 'Not Applicable',
 'NCSABodyType': '',
 'NCSAMake': '',
 'NCSAMapExcApprovedBy': '',
 'NCSAMapExcApprovedOn': '',
 'NCSAMappingException': '',
 'NCSAModel': '',
 'NCSANote': '',
 'NonLandUse': '',
 'Note': '',
 'OtherBusInfo': '',
 'OtherEngineInfo': '',
 'OtherMotorcycleInfo': '',
 'OtherRestraintSystemInfo': 'Seat Belt (Rr center position)',
 'OtherTrailerInfo': '',
 'ParkAssist': '',
 'PedestrianAutomaticEmergencyBraking': '',
 'PlantCity': 'MARYSVILLE',
 'PlantCompanyName': '',
 'PlantCountry': 'UNITED STATES (USA)',
 'PlantState': 'OHIO',
 'PossibleValues': '',
 'Pretensioner': '',
 'RearAutomaticEmergencyBraking': '',
 'RearCrossTrafficAlert': '',
 'RearVisibilitySystem': '',
 'SAEAutomationLevel': '',
 'SAEAutomationLevel_to': '',
 'SeatBeltsAll': 'Manual',
 'SeatRows': '',
 'Seats': '',
 'SemiautomaticHeadlampBeamSwitching': '',
 'Series': '',
 'Series2': '',
 'SteeringLocation': '',
 'SuggestedVIN': '',
 'TPMS': '',
 'TopSpeedMPH': '',
 'TrackWidth': '',
 'TractionControl': '',
 'TrailerBodyType': 'Not Applicable',
 'TrailerLength': '',
 'TrailerType': 'Not Applicable',
 'TransmissionSpeeds': '5',
 'TransmissionStyle': 'Automatic',
 'Trim': 'EX-V6',
 'Trim2': '',
 'Turbo': '',
 'VIN': '1HGCM82633A004352',
 'ValveTrainDesign': 'Single Overhead Cam (SOHC)',
 'VehicleDescriptor': '1HGCM826*3A',
 'VehicleType': 'PASSENGER CAR',
 'WheelBaseLong': '',
 'WheelBaseShort': '',
 'WheelBaseType': '',
 'WheelSizeFront': '',
 'WheelSizeRear': '',
 'WheelieMitigation': '',
 'Wheels': '',
 'Windows': ''}

In [4]:
important_vehicle_info = {
    "make": vehicle.get("Make"),
    "model": vehicle.get("Model"),
    "year": vehicle.get("ModelYear"),
    "body_type": vehicle.get("BodyClass")
    }

important_vehicle_info

{'make': 'HONDA', 'model': 'Accord', 'year': '2003', 'body_type': 'Coupe'}

In [5]:
vehicle_year = int(important_vehicle_info["year"])

if vehicle_year < 2015:
    risk_level = "HIGH"

else:
    risk_level = "NORMAL"

risk_level

'HIGH'

In [6]:
clean_vehicle_data = {
    "make": vehicle.get("Make"),
    "model": vehicle.get("Model"),
    "year": vehicle.get("ModelYear"),
    "body_type": vehicle.get("BodyClass")
    }

clean_vehicle_data

{'make': 'HONDA', 'model': 'Accord', 'year': '2003', 'body_type': 'Coupe'}

In [8]:
import pandas as pd 

contracts_df = pd.read_csv("../data/sample_car_contracts.csv")
contracts_df.head()

,id,customer_name,contract_type,vehicle_type,monthly_emi,interest_rate,tenure_months,clause_summary,risk_flag,issue_type,recommended_action
0,1,Rahul Mehta,Car Loan,Sedan,18500,9.5,48,Prepayment allowed only after 24 months with 5...,medium,High prepayment charges,Highlight prepayment penalty to user and sugge...
1,2,Anita Rao,Car Lease,SUV,22000,0.0,36,Lessee must pay for all maintenance and insurance,low,Standard maintenance clause,"No action, just explain maintenance responsibi..."
2,3,James Wilson,Car Loan,Hatchback,14500,11.2,60,Late payment fee of 3% per month on outstandin...,high,Aggressive late fee,Flag clause and suggest user request cap on la...
3,4,Meena Iyer,Car Lease,Sedan,21000,0.0,24,"Excess mileage charge of ₹12 per km over 15,00...",medium,High excess mileage rate,Warn user about extra mileage charges and reco...
4,5,Arjun Patel,Car Loan,SUV,27500,10.8,72,Floating interest rate linked to lender's inte...,high,Unclear interest benchmark,Explain floating rate risk and suggest asking ...

In [ ]:
# Data enrichment

def enrich_contract_with_vehicle(contract_row):
    vin = contract_row["vin"]
    vehicle = get_vehicle_details(vin)

    return {
        "contract_id": contract_row["contract_id"],
        "customer_name": contract_row["customer_name"],
        "vin": vin,
        "vehicle": {
            "make": vehicle.get("Make"),
            "model": vehicle.get("Model"),
            "year": vehicle.get("ModelYear")
        }
    }

In [16]:
combined_records = []

for _, row in contracts_df.iterrows():
    combined_records.append(enrich_contract_with_vehicle(row))

combined_records[:1]

KeyError: 'vin'

In [17]:
contracts_df.columns

Index(['id', 'customer_name', 'contract_type', 'vehicle_type', 'monthly_emi',
       'interest_rate', 'tenure_months', 'clause_summary', 'risk_flag',
       'issue_type', 'recommended_action'],
      dtype='object')

In [18]:
import pandas as pd 

contracts_df = pd.read_csv("../data/sample_car_contracts.csv")
contracts_df.head()

,id,customer_name,contract_type,vehicle_type,monthly_emi,interest_rate,tenure_months,clause_summary,risk_flag,issue_type,recommended_action
0,1,Rahul Mehta,Car Loan,Sedan,18500,9.5,48,Prepayment allowed only after 24 months with 5...,medium,High prepayment charges,Highlight prepayment penalty to user and sugge...
1,2,Anita Rao,Car Lease,SUV,22000,0.0,36,Lessee must pay for all maintenance and insurance,low,Standard maintenance clause,"No action, just explain maintenance responsibi..."
2,3,James Wilson,Car Loan,Hatchback,14500,11.2,60,Late payment fee of 3% per month on outstandin...,high,Aggressive late fee,Flag clause and suggest user request cap on la...
3,4,Meena Iyer,Car Lease,Sedan,21000,0.0,24,"Excess mileage charge of ₹12 per km over 15,00...",medium,High excess mileage rate,Warn user about extra mileage charges and reco...
4,5,Arjun Patel,Car Loan,SUV,27500,10.8,72,Floating interest rate linked to lender's inte...,high,Unclear interest benchmark,Explain floating rate risk and suggest asking ...

In [19]:
contracts_df["vin"] = "1HGCM82633A004352"

In [20]:
contracts_df[["vin"]].head()

                 vin
0  1HGCM82633A004352
1  1HGCM82633A004352
2  1HGCM82633A004352
3  1HGCM82633A004352
4  1HGCM82633A004352

In [21]:
contracts_df.to_csv("../data/sample_car_contracts_with_vin.csv", index=False)

In [23]:
combined_records = []

for _, row in contracts_df.iterrows():
    combined_records.append(enrich_contract_with_vehicle(row))

KeyError: 'contract_id'

In [24]:
important_vehicle_info = {
    "make": vehicle.get("Make"),
    "model": vehicle.get("Model"),
    "year": vehicle.get("ModelYear"),
    "body_type": vehicle.get("BodyClass")
    }

important_vehicle_info

{'make': 'HONDA', 'model': 'Accord', 'year': '2003', 'body_type': 'Coupe'}

In [25]:
vehicle_year = int(important_vehicle_info["year"])

if vehicle_year < 2015:
    risk_level = "HIGH"

else:
    risk_level = "NORMAL"

risk_level

'HIGH'

In [26]:
clean_vehicle_data = {
    "make": vehicle.get("Make"),
    "model": vehicle.get("Model"),
    "year": vehicle.get("ModelYear"),
    "body_type": vehicle.get("BodyClass")
    }

clean_vehicle_data

{'make': 'HONDA', 'model': 'Accord', 'year': '2003', 'body_type': 'Coupe'}

In [27]:
import pandas as pd 

contracts_df = pd.read_csv("../data/sample_car_contracts_with_vin.csv")
contracts_df.head()

,id,customer_name,contract_type,vehicle_type,monthly_emi,interest_rate,tenure_months,clause_summary,risk_flag,issue_type,recommended_action,vin
0,1,Rahul Mehta,Car Loan,Sedan,18500,9.5,48,Prepayment allowed only after 24 months with 5...,medium,High prepayment charges,Highlight prepayment penalty to user and sugge...,1HGCM82633A004352
1,2,Anita Rao,Car Lease,SUV,22000,0.0,36,Lessee must pay for all maintenance and insurance,low,Standard maintenance clause,"No action, just explain maintenance responsibi...",1HGCM82633A004352
2,3,James Wilson,Car Loan,Hatchback,14500,11.2,60,Late payment fee of 3% per month on outstandin...,high,Aggressive late fee,Flag clause and suggest user request cap on la...,1HGCM82633A004352
3,4,Meena Iyer,Car Lease,Sedan,21000,0.0,24,"Excess mileage charge of ₹12 per km over 15,00...",medium,High excess mileage rate,Warn user about extra mileage charges and reco...,1HGCM82633A004352
4,5,Arjun Patel,Car Loan,SUV,27500,10.8,72,Floating interest rate linked to lender's inte...,high,Unclear interest benchmark,Explain floating rate risk and suggest asking ...,1HGCM82633A004352

In [28]:
combined_records = []

for _, row in contracts_df.iterrows():
    combined_records.append(enrich_contract_with_vehicle(row))

KeyError: 'contract_id'

In [29]:
contracts_df.columns

Index(['id', 'customer_name', 'contract_type', 'vehicle_type', 'monthly_emi',
       'interest_rate', 'tenure_months', 'clause_summary', 'risk_flag',
       'issue_type', 'recommended_action', 'vin'],
      dtype='object')

In [2]:
import pandas as pd 

contracts_df = pd.read_csv("../data/sample_car_contracts_with_vin.csv")
contracts_df.head()

,id,customer_name,contract_type,vehicle_type,monthly_emi,interest_rate,tenure_months,clause_summary,risk_flag,issue_type,recommended_action,vin
0,1,Rahul Mehta,Car Loan,Sedan,18500,9.5,48,Prepayment allowed only after 24 months with 5...,medium,High prepayment charges,Highlight prepayment penalty to user and sugge...,1HGCM82633A004352
1,2,Anita Rao,Car Lease,SUV,22000,0.0,36,Lessee must pay for all maintenance and insurance,low,Standard maintenance clause,"No action, just explain maintenance responsibi...",1HGCM82633A004352
2,3,James Wilson,Car Loan,Hatchback,14500,11.2,60,Late payment fee of 3% per month on outstandin...,high,Aggressive late fee,Flag clause and suggest user request cap on la...,1HGCM82633A004352
3,4,Meena Iyer,Car Lease,Sedan,21000,0.0,24,"Excess mileage charge of ₹12 per km over 15,00...",medium,High excess mileage rate,Warn user about extra mileage charges and reco...,1HGCM82633A004352
4,5,Arjun Patel,Car Loan,SUV,27500,10.8,72,Floating interest rate linked to lender's inte...,high,Unclear interest benchmark,Explain floating rate risk and suggest asking ...,1HGCM82633A004352

In [3]:
import requests

def get_vehicle_details(vin):
    url = f"https://vpic.nhtsa.dot.gov/api/vehicles/DecodeVinValues/{vin}?format=json"
    response = requests.get(url)
    return response.json()["Results"][0]

In [4]:
def extract_vehicle_info(vehicle_data):
    return {
        "make": vehicle_data.get("Make"),
        "model": vehicle_data.get("Model"),
        "year": vehicle_data.get("ModelYear")
    }

In [7]:
def extract_sla_details(row):
    """
    Extract SLA-related information from a contract row.
    Returns SLA data in JSON format.
    """

    sla_data = {
        "monthly_emi": row.get("monthly_emi"),
        "interest_rate": row.get("interest_rate"),
        "tenure_months": row.get("tenure_months"),
        "risk_flag": row.get("risk_flag"),
        "issue_type": row.get("issue_type"),
        "recommended_action": row.get("recommended_action")
    }

    return sla_data

In [5]:
def enrich_contract_with_vehicle(row):
    vehicle_raw = get_vehicle_details(row["vin"])
    vehicle_info = extract_vehicle_info(vehicle_raw)

    return {
        "contract_id": row["id"],
        "customer_name": row["customer_name"],
        "contract_type": row["contract_type"],
        "sla": extract_sla_details(row),
        "vehicle": vehicle_info
    }

In [8]:
combined_records = []

for _, row in contracts_df.iterrows():
    combined_records.append(enrich_contract_with_vehicle(row))

combined_records[:1]

[{'contract_id': 1,
  'customer_name': 'Rahul Mehta',
  'contract_type': 'Car Loan',
  'sla': {'monthly_emi': 18500,
   'interest_rate': 9.5,
   'tenure_months': 48,
   'risk_flag': 'medium',
   'issue_type': 'High prepayment charges',
   'recommended_action': 'Highlight prepayment penalty to user and suggest negotiation for lower fee'},
  'vehicle': {'make': 'HONDA', 'model': 'Accord', 'year': '2003'}}]

In [9]:
final_df = pd.DataFrame(combined_records)
final_df.head()

,contract_id,customer_name,contract_type,sla,vehicle
0,1,Rahul Mehta,Car Loan,"{'monthly_emi': 18500, 'interest_rate': 9.5, '...","{'make': 'HONDA', 'model': 'Accord', 'year': '..."
1,2,Anita Rao,Car Lease,"{'monthly_emi': 22000, 'interest_rate': 0.0, '...","{'make': 'HONDA', 'model': 'Accord', 'year': '..."
2,3,James Wilson,Car Loan,"{'monthly_emi': 14500, 'interest_rate': 11.2, ...","{'make': 'HONDA', 'model': 'Accord', 'year': '..."
3,4,Meena Iyer,Car Lease,"{'monthly_emi': 21000, 'interest_rate': 0.0, '...","{'make': 'HONDA', 'model': 'Accord', 'year': '..."
4,5,Arjun Patel,Car Loan,"{'monthly_emi': 27500, 'interest_rate': 10.8, ...","{'make': 'HONDA', 'model': 'Accord', 'year': '..."