In [1]:
import pandas as pd
df=pd.read_csv("../data/sample_car_contracts_with_vin.csv")
df.head()

,id,customer_name,contract_type,vehicle_type,monthly_emi,interest_rate,tenure_months,clause_summary,risk_flag,issue_type,recommended_action,vin
0,1,Rahul Mehta,Car Loan,Sedan,18500,9.5,48,Prepayment allowed only after 24 months with 5...,medium,High prepayment charges,Highlight prepayment penalty to user and sugge...,1HGCM82633A004352
1,2,Anita Rao,Car Lease,SUV,22000,0.0,36,Lessee must pay for all maintenance and insurance,low,Standard maintenance clause,"No action, just explain maintenance responsibi...",1HGCM82633A004352
2,3,James Wilson,Car Loan,Hatchback,14500,11.2,60,Late payment fee of 3% per month on outstandin...,high,Aggressive late fee,Flag clause and suggest user request cap on la...,1HGCM82633A004352
3,4,Meena Iyer,Car Lease,Sedan,21000,0.0,24,"Excess mileage charge of ₹12 per km over 15,00...",medium,High excess mileage rate,Warn user about extra mileage charges and reco...,1HGCM82633A004352
4,5,Arjun Patel,Car Loan,SUV,27500,10.8,72,Floating interest rate linked to lender's inte...,high,Unclear interest benchmark,Explain floating rate risk and suggest asking ...,1HGCM82633A004352

In [2]:
def ocr_extract_contract_text(file_path):
    """
    Simulated OCR extraction.
    In real production: Tessaract / Google Vision API
    """
    print("Performing OCR on upload contract...")

    ocr_text = """
    Contract_ID: 5
    Customer Name: Arjun
    Vehicle Type: SUV
    Monthly_EMI: 25000
    Interest_Rate: 10.8
    Tenure_Months: 72
    Risk Flag: High
    """

    return ocr_text

In [3]:
def parse_ocr_text(ocr_text):
    """
    Converts OCR text into structured contract data
    """
    return{
            "id": 5,
            "customer_name": "Arjun",
            "vehicle_type": "SUV",
            "monthly_emi": 25000,
            "interest_rate": 10.8,
            "tenure_months": 72,
            "risk_flag":"high"
    }

In [4]:
import pandas as pd
df=pd.read_csv("../data/sample_car_contracts_with_vin.csv")
df.head()

,id,customer_name,contract_type,vehicle_type,monthly_emi,interest_rate,tenure_months,clause_summary,risk_flag,issue_type,recommended_action,vin
0,1,Rahul Mehta,Car Loan,Sedan,18500,9.5,48,Prepayment allowed only after 24 months with 5...,medium,High prepayment charges,Highlight prepayment penalty to user and sugge...,1HGCM82633A004352
1,2,Anita Rao,Car Lease,SUV,22000,0.0,36,Lessee must pay for all maintenance and insurance,low,Standard maintenance clause,"No action, just explain maintenance responsibi...",1HGCM82633A004352
2,3,James Wilson,Car Loan,Hatchback,14500,11.2,60,Late payment fee of 3% per month on outstandin...,high,Aggressive late fee,Flag clause and suggest user request cap on la...,1HGCM82633A004352
3,4,Meena Iyer,Car Lease,Sedan,21000,0.0,24,"Excess mileage charge of ₹12 per km over 15,00...",medium,High excess mileage rate,Warn user about extra mileage charges and reco...,1HGCM82633A004352
4,5,Arjun Patel,Car Loan,SUV,27500,10.8,72,Floating interest rate linked to lender's inte...,high,Unclear interest benchmark,Explain floating rate risk and suggest asking ...,1HGCM82633A004352

In [5]:
# Simulate the Backened Contract Lookup (Upload API Logic)

def get_contract_by_id(id):
    record =df[df["id"]==id]

    if record.empty:
        return None
    return record.iloc[0].to_dict()

In [6]:
# Test Contract Lookup

contract = get_contract_by_id(5)

In [7]:
# Negotiation Logic

def negotiation_advice(contract):
    advice = []

    if contract["interest_rate"] > 10:
        advice.append("Try negotiating interest rate")

    if contract["tenure_months"] > 60:
        advice.append("Ask for shorter tenure")

    if contract["risk_flag"] == "high":
        advice.append("Proceed carefully or compare other offers")

    if not advice:
        advice.append("Contract terms look reasonable")

    return advice

In [8]:
contract = get_contract_by_id(5)
negotiation_advice(contract)

['Try negotiating interest rate',
 'Ask for shorter tenure',
 'Proceed carefully or compare other offers']

In [9]:
final_output = {
    "contract_id" : contract["id"],
    "customer_name" : contract["customer_name"],
    "vehicle_type" : contract["vehicle_type"],
    "monthly_emi" : contract["monthly_emi"],
    "interest_rate" : contract["interest_rate"],
    "tenure_months" : contract["tenure_months"],
    "risk_flag" : contract["risk_flag"],
    "negotiation_advice" : negotiation_advice   
}

final_output

{'contract_id': 5,
 'customer_name': 'Arjun Patel',
 'vehicle_type': 'SUV',
 'monthly_emi': 27500,
 'interest_rate': 10.8,
 'tenure_months': 72,
 'risk_flag': 'high',
 'negotiation_advice': <function __main__.negotiation_advice(contract)>}