In [11]:
import pandas as pd
df = pd.read_csv("../data/contract_evaluation_dataset_tulasi-vasireddy.csv")
df.head()

,contract_text,expected_apr,expected_term,expected_payment,expected_penalty
0,The loan agreement offers an APR of 8.5% for a...,8.5,36.0,310.0,Late payment penalty of $40
1,This car loan has an APR of 7.9% with a repaym...,7.9,48.0,275.0,NaN
2,The borrower agrees to a loan term of 60 month...,NaN,60.0,350.0,Penalty of 3% on delayed payments
3,The agreement specifies a loan duration of 24 ...,NaN,24.0,NaN,NaN
4,"In case of late payment, a fee of $100 will be...",NaN,NaN,NaN,Late fee of $100

In [12]:
expected_output = {
    "apr": None,
    "term_months": None,
    "monthly_payment": None,
    "penalty_clause": None
}

In [6]:
PROMPT = """
Extract ONLY the following fields from the contract text:
- APR
- Term in months
- Monthly payment
- Penalty clause

Rules:
- Return JSON only
- Return null if missing
- Do NOT infer values

Contract Text:
\"\"\"{contract_text}\"\"\"
"""

In [13]:
def extract_sla(contract_text):
    return {
        "apr": None,
        "term_months": None,
        "monthly_payment": None,
        "penalty_clause": None
    }

In [14]:
import pandas as pd

In [15]:
df = pd.read_csv("../data/contract_evaluation_dataset_tulasi-vasireddy.csv")
df.head()

,contract_text,expected_apr,expected_term,expected_payment,expected_penalty
0,The loan agreement offers an APR of 8.5% for a...,8.5,36.0,310.0,Late payment penalty of $40
1,This car loan has an APR of 7.9% with a repaym...,7.9,48.0,275.0,NaN
2,The borrower agrees to a loan term of 60 month...,NaN,60.0,350.0,Penalty of 3% on delayed payments
3,The agreement specifies a loan duration of 24 ...,NaN,24.0,NaN,NaN
4,"In case of late payment, a fee of $100 will be...",NaN,NaN,NaN,Late fee of $100

In [16]:
sample_df = df.head(5)
sample_df

,contract_text,expected_apr,expected_term,expected_payment,expected_penalty
0,The loan agreement offers an APR of 8.5% for a...,8.5,36.0,310.0,Late payment penalty of $40
1,This car loan has an APR of 7.9% with a repaym...,7.9,48.0,275.0,NaN
2,The borrower agrees to a loan term of 60 month...,NaN,60.0,350.0,Penalty of 3% on delayed payments
3,The agreement specifies a loan duration of 24 ...,NaN,24.0,NaN,NaN
4,"In case of late payment, a fee of $100 will be...",NaN,NaN,NaN,Late fee of $100

In [17]:
def extract_sla(contract_text):
    return {
        "apr": None,
        "term_months": None,
        "monthly_payment": None,
        "penalty_clause": None
    }

In [18]:
results = [extract_sla(text) for text in sample_df["contract_text"]]
results_df = pd.DataFrame(results)
results_df

    apr term_months monthly_payment penalty_clause
0  None        None            None           None
1  None        None            None           None
2  None        None            None           None
3  None        None            None           None
4  None        None            None           None

In [19]:
comparison_df = sample_df.reset_index(drop=True)

comparison_df["apr_match"] = (
    comparison_df["expected_apr"] == results_df["apr"]
).astype(int)

comparison_df["term_match"] = (
    comparison_df["expected_term"] == results_df["term_months"]
).astype(int)

comparison_df["payment_match"] = (
    comparison_df["expected_payment"] == results_df["monthly_payment"]
).astype(int)

comparison_df["penalty_match"] = (
    comparison_df["expected_penalty"] == results_df["penalty_clause"]
).astype(int)

comparison_df

,contract_text,expected_apr,expected_term,expected_payment,expected_penalty,apr_match,term_match,payment_match,penalty_match
0,The loan agreement offers an APR of 8.5% for a...,8.5,36.0,310.0,Late payment penalty of $40,0,0,0,0
1,This car loan has an APR of 7.9% with a repaym...,7.9,48.0,275.0,NaN,0,0,0,0
2,The borrower agrees to a loan term of 60 month...,NaN,60.0,350.0,Penalty of 3% on delayed payments,0,0,0,0
3,The agreement specifies a loan duration of 24 ...,NaN,24.0,NaN,NaN,0,0,0,0
4,"In case of late payment, a fee of $100 will be...",NaN,NaN,NaN,Late fee of $100,0,0,0,0

In [2]:
import requests

In [3]:
def get_vehicle_details(vin):
    pass

In [4]:
import requests
def get_vehicle_details(vin):
    url = f"https://vpic.nhtsa.dot.gov/api/vehicles/DecodeVinValues/{vin}?format=json"
    response = requests.get(url)
    data = response.json()
    return data["Results"][0]

In [5]:
vehicle = get_vehicle_details("1HGCM82633A004352")
vehicle

{'ABS': '',
 'ActiveSafetySysNote': '',
 'AdaptiveCruiseControl': '',
 'AdaptiveDrivingBeam': '',
 'AdaptiveHeadlights': '',
 'AdditionalErrorText': '',
 'AirBagLocCurtain': '1st and 2nd Rows',
 'AirBagLocFront': '1st Row (Driver and Passenger)',
 'AirBagLocKnee': '',
 'AirBagLocSeatCushion': '',
 'AirBagLocSide': '1st Row (Driver and Passenger)',
 'AutoReverseSystem': '',
 'AutomaticPedestrianAlertingSound': '',
 'AxleConfiguration': '',
 'Axles': '',
 'BasePrice': '',
 'BatteryA': '',
 'BatteryA_to': '',
 'BatteryCells': '',
 'BatteryInfo': '',
 'BatteryKWh': '',
 'BatteryKWh_to': '',
 'BatteryModules': '',
 'BatteryPacks': '',
 'BatteryType': '',
 'BatteryV': '',
 'BatteryV_to': '',
 'BedLengthIN': '',
 'BedType': 'Not Applicable',
 'BlindSpotIntervention': '',
 'BlindSpotMon': '',
 'BodyCabType': 'Not Applicable',
 'BodyClass': 'Coupe',
 'BrakeSystemDesc': '',
 'BrakeSystemType': '',
 'BusFloorConfigType': 'Not Applicable',
 'BusLength': '',
 'BusType': 'Not Applicable',
 'CAN_AACN': '',
 'CIB': '',
 'CashForClunkers': '',
 'ChargerLevel': '',
 'ChargerPowerKW': '',
 'CombinedBrakingSystem': '',
 'CoolingType': '',
 'CurbWeightLB': '',
 'CustomMotorcycleType': 'Not Applicable',
 'DaytimeRunningLight': '',
 'DestinationMarket': '',
 'DisplacementCC': '2998.832712',
 'DisplacementCI': '183',
 'DisplacementL': '2.998832712',
 'Doors': '2',
 'DriveType': '',
 'DriverAssist': '',
 'DynamicBrakeSupport': '',
 'EDR': '',
 'ESC': '',
 'EVDriveUnit': '',
 'ElectrificationLevel': '',
 'EngineConfiguration': 'V-Shaped',
 'EngineCycles': '',
 'EngineCylinders': '6',
 'EngineHP': '240',
 'EngineHP_to': '',
 'EngineKW': '',
 'EngineManufacturer': '',
 'EngineModel': 'J30A4',
 'EntertainmentSystem': '',
 'ErrorCode': '0',
 'ErrorText': '0 - VIN decoded clean. Check Digit (9th position) is correct',
 'ForwardCollisionWarning': '',
 'FuelInjectionType': '',
 'FuelTankMaterial': '',
 'FuelTankType': '',
 'FuelTypePrimary': 'Gasoline',
 'FuelTypeSecondary': '',
 'GCWR': '',
 'GCWR_to': '',
 'GVWR': 'Class 1C: 4,001 - 5,000 lb (1,814 - 2,268 kg)',
 'GVWR_to': 'Class 1: 6,000 lb or less (2,722 kg or less)',
 'KeylessIgnition': '',
 'LaneCenteringAssistance': '',
 'LaneDepartureWarning': '',
 'LaneKeepSystem': '',
 'LowerBeamHeadlampLightSource': '',
 'Make': 'HONDA',
 'MakeID': '474',
 'Manufacturer': 'AMERICAN HONDA MOTOR CO., INC.',
 'ManufacturerId': '988',
 'Model': 'Accord',
 'ModelID': '1861',
 'ModelYear': '2003',
 'MotorcycleChassisType': 'Not Applicable',
 'MotorcycleSuspensionType': 'Not Applicable',
 'NCSABodyType': '',
 'NCSAMake': '',
 'NCSAMapExcApprovedBy': '',
 'NCSAMapExcApprovedOn': '',
 'NCSAMappingException': '',
 'NCSAModel': '',
 'NCSANote': '',
 'NonLandUse': '',
 'Note': '',
 'OtherBusInfo': '',
 'OtherEngineInfo': '',
 'OtherMotorcycleInfo': '',
 'OtherRestraintSystemInfo': 'Seat Belt (Rr center position)',
 'OtherTrailerInfo': '',
 'ParkAssist': '',
 'PedestrianAutomaticEmergencyBraking': '',
 'PlantCity': 'MARYSVILLE',
 'PlantCompanyName': '',
 'PlantCountry': 'UNITED STATES (USA)',
 'PlantState': 'OHIO',
 'PossibleValues': '',
 'Pretensioner': '',
 'RearAutomaticEmergencyBraking': '',
 'RearCrossTrafficAlert': '',
 'RearVisibilitySystem': '',
 'SAEAutomationLevel': '',
 'SAEAutomationLevel_to': '',
 'SeatBeltsAll': 'Manual',
 'SeatRows': '',
 'Seats': '',
 'SemiautomaticHeadlampBeamSwitching': '',
 'Series': '',
 'Series2': '',
 'SteeringLocation': '',
 'SuggestedVIN': '',
 'TPMS': '',
 'TopSpeedMPH': '',
 'TrackWidth': '',
 'TractionControl': '',
 'TrailerBodyType': 'Not Applicable',
 'TrailerLength': '',
 'TrailerType': 'Not Applicable',
 'TransmissionSpeeds': '5',
 'TransmissionStyle': 'Automatic',
 'Trim': 'EX-V6',
 'Trim2': '',
 'Turbo': '',
 'VIN': '1HGCM82633A004352',
 'ValveTrainDesign': 'Single Overhead Cam (SOHC)',
 'VehicleDescriptor': '1HGCM826*3A',
 'VehicleType': 'PASSENGER CAR',
 'WheelBaseLong': '',
 'WheelBaseShort': '',
 'WheelBaseType': '',
 'WheelSizeFront': '',
 'WheelSizeRear': '',
 'WheelieMitigation': '',
 'Wheels': '',
 'Windows': ''}

In [9]:
important_vehicle_info = {
    "make": vehicle.get("Make"),
    "model": vehicle.get("Model"),
    "year": vehicle.get("ModelYear"),
    "body_type": vehicle.get("BodyClass")
}
important_vehicle_info

{'make': 'HONDA', 'model': 'Accord', 'year': '2003', 'body_type': 'Coupe'}

In [11]:
vehicle_year = int(important_vehicle_info["year"])
if vehicle_year < 2015:
    risk_level = "HIGH"
else:
    risk_level = "NORMAL"
risk_level

'HIGH'

In [12]:
clean_vehicle_data = {
    "make": vehicle.get("Make"),
    "model": vehicle.get("Model"),
    "year": vehicle.get("ModelYear"),
    "body_type": vehicle.get("BodyClass")
}
clean_vehicle_data

{'make': 'HONDA', 'model': 'Accord', 'year': '2003', 'body_type': 'Coupe'}

In [13]:
import pandas as pd
contracts_df = pd.read_csv("../data/sample_car_contracts.csv")
contracts_df.head()

,id,customer_name,contract_type,vehicle_type,monthly_emi,interest_rate,tenure_months,clause_summary,risk_flag,issue_type,recommended_action
0,1,Rahul Mehta,Car Loan,Sedan,18500,9.5,48,Prepayment allowed only after 24 months with 5...,medium,High prepayment charges,Highlight prepayment penalty to user and sugge...
1,2,Anita Rao,Car Lease,SUV,22000,0.0,36,Lessee must pay for all maintenance and insurance,low,Standard maintenance clause,"No action, just explain maintenance responsibi..."
2,3,James Wilson,Car Loan,Hatchback,14500,11.2,60,Late payment fee of 3% per month on outstandin...,high,Aggressive late fee,Flag clause and suggest user request cap on la...
3,4,Meena Iyer,Car Lease,Sedan,21000,0.0,24,"Excess mileage charge of ₹12 per km over 15,00...",medium,High excess mileage rate,Warn user about extra mileage charges and reco...
4,5,Arjun Patel,Car Loan,SUV,27500,10.8,72,Floating interest rate linked to lender's inte...,high,Unclear interest benchmark,Explain floating rate risk and suggest asking ...

In [14]:
def enrich_contract_with_vehicle(contract_row):
    vin = contract_row["vin"]
    vehicle = get_vehicle_details(vin)
    return {
        "contract_id": contract_row["contract_id"],
        "customer_name": contract_row["customer_name"],
        "vin": vin,
        "vehicle": {
            "make": vehicle.get("make"),
            "model": vehicle.get("model"),
            "year": vehicle.get("ModelYear")
        }
    }

In [15]:
contracts_df.columns

Index(['id', 'customer_name', 'contract_type', 'vehicle_type', 'monthly_emi',
       'interest_rate', 'tenure_months', 'clause_summary', 'risk_flag',
       'issue_type', 'recommended_action'],
      dtype='object')

In [16]:
contracts_df["vin"] = "1HGCM82633A004352"

In [17]:
contracts_df[["vin"]].head()

                 vin
0  1HGCM82633A004352
1  1HGCM82633A004352
2  1HGCM82633A004352
3  1HGCM82633A004352
4  1HGCM82633A004352

In [18]:
contracts_df.to_csv("../data/sample_car_contracts_with_vin.csv", index=False)

In [21]:
def extract_sla_details(row):
 """
 Simulates LLM-based SLA extraction.
 Returns SLA details in JSON format.
 """
 return {
 "monthly_emi": row["monthly_emi"],
 "interest_rate": row["interest_rate"],
 "tenure_months": row["tenure_months"],
 "risk_flag": row["risk_flag"],
 "issue_type": row["issue_type"],
 "recommended_action": row["recommended_action"]
 }

In [22]:
import pandas as pd
contracts_df = pd.read_csv("../data/sample_car_contracts_with_vin.csv")
contracts_df.head()

,id,customer_name,contract_type,vehicle_type,monthly_emi,interest_rate,tenure_months,clause_summary,risk_flag,issue_type,recommended_action,vin
0,1,Rahul Mehta,Car Loan,Sedan,18500,9.5,48,Prepayment allowed only after 24 months with 5...,medium,High prepayment charges,Highlight prepayment penalty to user and sugge...,1HGCM82633A004352
1,2,Anita Rao,Car Lease,SUV,22000,0.0,36,Lessee must pay for all maintenance and insurance,low,Standard maintenance clause,"No action, just explain maintenance responsibi...",1HGCM82633A004352
2,3,James Wilson,Car Loan,Hatchback,14500,11.2,60,Late payment fee of 3% per month on outstandin...,high,Aggressive late fee,Flag clause and suggest user request cap on la...,1HGCM82633A004352
3,4,Meena Iyer,Car Lease,Sedan,21000,0.0,24,"Excess mileage charge of ₹12 per km over 15,00...",medium,High excess mileage rate,Warn user about extra mileage charges and reco...,1HGCM82633A004352
4,5,Arjun Patel,Car Loan,SUV,27500,10.8,72,Floating interest rate linked to lender's inte...,high,Unclear interest benchmark,Explain floating rate risk and suggest asking ...,1HGCM82633A004352

In [23]:
sla_records = []
for _, row in contracts_df.iterrows():
 sla_records.append({
 "contract_id": row["id"],
 "customer_name": row["customer_name"],
 "sla": extract_sla_details(row)
 })
sla_df = pd.DataFrame(sla_records)
sla_df.head()

,contract_id,customer_name,sla
0,1,Rahul Mehta,"{'monthly_emi': 18500, 'interest_rate': 9.5, '..."
1,2,Anita Rao,"{'monthly_emi': 22000, 'interest_rate': 0.0, '..."
2,3,James Wilson,"{'monthly_emi': 14500, 'interest_rate': 11.2, ..."
3,4,Meena Iyer,"{'monthly_emi': 21000, 'interest_rate': 0.0, '..."
4,5,Arjun Patel,"{'monthly_emi': 27500, 'interest_rate': 10.8, ..."

In [24]:
sla_df.to_csv("../data/milestone2_sla_output.csv", index=False)

In [25]:
sla_df.sample(5)

,contract_id,customer_name,sla
5,6,Sana Khan,"{'monthly_emi': 16500, 'interest_rate': 0.0, '..."
2,3,James Wilson,"{'monthly_emi': 14500, 'interest_rate': 11.2, ..."
0,1,Rahul Mehta,"{'monthly_emi': 18500, 'interest_rate': 9.5, '..."
3,4,Meena Iyer,"{'monthly_emi': 21000, 'interest_rate': 0.0, '..."
11,12,Imran Ali,"{'monthly_emi': 24500, 'interest_rate': 0.0, '..."

In [27]:
import requests
def get_vehicle_details(vin):
 url =f"https://vpic.nhtsa.dot.gov/api/vehicles/DecodeVinValues/{vin}?format=json"
 response = requests.get(url)
 return response.json()["Results"][0]

In [28]:
def extract_vehicle_info(vehicle_raw):
 return {
 "make": vehicle_raw.get("Make"),
 "model": vehicle_raw.get("Model"),
 "year": vehicle_raw.get("ModelYear")
 }

In [29]:
def enrich_contract_with_vehicle(row):
 vehicle_raw = get_vehicle_details(row["vin"])
 vehicle_info = extract_vehicle_info(vehicle_raw)
 return {
 "contract_id": row["id"],
 "customer_name": row["customer_name"],
 "contract_type": row["contract_type"],
 "sla": extract_sla_details(row),
 "vehicle": vehicle_info
 }

In [30]:
combined_records = []
for _, row in contracts_df.iterrows():
 combined_records.append(enrich_contract_with_vehicle(row))
combined_df = pd.DataFrame(combined_records)
combined_df.head()

,contract_id,customer_name,contract_type,sla,vehicle
0,1,Rahul Mehta,Car Loan,"{'monthly_emi': 18500, 'interest_rate': 9.5, '...","{'make': 'HONDA', 'model': 'Accord', 'year': '..."
1,2,Anita Rao,Car Lease,"{'monthly_emi': 22000, 'interest_rate': 0.0, '...","{'make': 'HONDA', 'model': 'Accord', 'year': '..."
2,3,James Wilson,Car Loan,"{'monthly_emi': 14500, 'interest_rate': 11.2, ...","{'make': 'HONDA', 'model': 'Accord', 'year': '..."
3,4,Meena Iyer,Car Lease,"{'monthly_emi': 21000, 'interest_rate': 0.0, '...","{'make': 'HONDA', 'model': 'Accord', 'year': '..."
4,5,Arjun Patel,Car Loan,"{'monthly_emi': 27500, 'interest_rate': 10.8, ...","{'make': 'HONDA', 'model': 'Accord', 'year': '..."

In [31]:
combined_df.to_csv("../data/milestone2_evaluation_output.csv", index=False)