In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv('../notebook/Milestone1_pavan-srinivas.csv')
df.head()

,contract_id,raw_text,apr,term_months,monthly_payment,penalty_clause,recommended_action,risk_flag
0,1,This contract between Prime Auto and Emily Sto...,10.49,24,959,NaN,Approve,Low
1,2,This contract between ABC Motors and Priya Sha...,3.78,24,804,Early termination fee $300,Approve,Low
2,3,This contract between DriveEasy Finance and Sa...,5.41,24,774,Late fee $50,Reject,High
3,4,This contract between National Motors and Alex...,5.26,48,1028,Late fee $25,Approve,High
4,5,This contract between National Motors and John...,5.97,36,1180,NaN,Approve,Low

In [2]:
#Ground Truth Simulation

df['expected_apr']=df['apr']
df['expected term']=df['term_months']
df['expected_payment']=df['monthly_payment']
df['expected_penalty']=df['penalty_clause']

In [3]:
df.columns 

df["expected_penalty"] = df["expected_penalty"] 
df[["expected_penalty"]].head()

             expected_penalty
0                         NaN
1  Early termination fee $300
2                Late fee $50
3                Late fee $25
4                         NaN

In [4]:
# if extracted APR exactly matches expected
# APR score 1
# if not score 0

# if extracted term months equals expected
# term months score 1
# else score 0

# if extracted penalty text matches expected
# penalty score 1
# else score 0

# Create expected columns from existing ground-truth values
df["expected_apr"] = df["apr"]
df["expected_term"] = df["term_months"]
df["expected_penalty"] = df["penalty_clause"]

# Scoring logic
df["apr_score"] = (df["apr"] == df["expected_apr"]).astype(int)
df["term_score"] = (df["term_months"] == df["expected_term"]).astype(int)
df["penalty_score"] = (df["penalty_clause"] == df["expected_penalty"]).astype(int)

# Total score
df["total_score"] = (
    df["apr_score"] +
    df["term_score"] +
    df["penalty_score"]
)

In [5]:
df["apr_score"] = (df["apr"] == df["expected_apr"]).astype(int)

In [6]:
df["term_score"] = (df["term_months"] == df["expected_term"]).astype(int)

In [7]:
df["penalty_score"] = (df["penalty_clause"] == df["expected_penalty"]).astype(int)

In [8]:
df["total_score"] = (df["apr_score"] + df["term_score"] + df["penalty_score"])

In [9]:
df["quality_percent"] = (df["total_score"]/3)*100

In [10]:
df[["apr_score","term_score","penalty_score","total_score","quality_percent"]].head()

   apr_score  term_score  penalty_score  total_score  quality_percent
0          1           1              0            2        66.666667
1          1           1              1            3       100.000000
2          1           1              1            3       100.000000
3          1           1              1            3       100.000000
4          1           1              0            2        66.666667

In [11]:
df.to_csv("../data/milestone2_evaluation_output.csv",index=False)

In [12]:
import requests

In [13]:
def get_vehicle_details(vin):
    pass

In [14]:
# API call code

import requests

def get_vehicle_details(vin):
    url = f"https://vpic.nhtsa.dot.gov/api/vehicles/DecodeVinValues/{vin}?format=json"
    response = requests.get(url)
    data = response.json()
    return data["Results"][0]

In [15]:
vehicle = get_vehicle_details("1HGCM82633A004352")
vehicle

{'ABS': '',
 'ActiveSafetySysNote': '',
 'AdaptiveCruiseControl': '',
 'AdaptiveDrivingBeam': '',
 'AdaptiveHeadlights': '',
 'AdditionalErrorText': '',
 'AirBagLocCurtain': '1st and 2nd Rows',
 'AirBagLocFront': '1st Row (Driver and Passenger)',
 'AirBagLocKnee': '',
 'AirBagLocSeatCushion': '',
 'AirBagLocSide': '1st Row (Driver and Passenger)',
 'AutoReverseSystem': '',
 'AutomaticPedestrianAlertingSound': '',
 'AxleConfiguration': '',
 'Axles': '',
 'BasePrice': '',
 'BatteryA': '',
 'BatteryA_to': '',
 'BatteryCells': '',
 'BatteryInfo': '',
 'BatteryKWh': '',
 'BatteryKWh_to': '',
 'BatteryModules': '',
 'BatteryPacks': '',
 'BatteryType': '',
 'BatteryV': '',
 'BatteryV_to': '',
 'BedLengthIN': '',
 'BedType': 'Not Applicable',
 'BlindSpotIntervention': '',
 'BlindSpotMon': '',
 'BodyCabType': 'Not Applicable',
 'BodyClass': 'Coupe',
 'BrakeSystemDesc': '',
 'BrakeSystemType': '',
 'BusFloorConfigType': 'Not Applicable',
 'BusLength': '',
 'BusType': 'Not Applicable',
 'CAN_AACN': '',
 'CIB': '',
 'CashForClunkers': '',
 'ChargerLevel': '',
 'ChargerPowerKW': '',
 'CombinedBrakingSystem': '',
 'CoolingType': '',
 'CurbWeightLB': '',
 'CustomMotorcycleType': 'Not Applicable',
 'DaytimeRunningLight': '',
 'DestinationMarket': '',
 'DisplacementCC': '2998.832712',
 'DisplacementCI': '183',
 'DisplacementL': '2.998832712',
 'Doors': '2',
 'DriveType': '',
 'DriverAssist': '',
 'DynamicBrakeSupport': '',
 'EDR': '',
 'ESC': '',
 'EVDriveUnit': '',
 'ElectrificationLevel': '',
 'EngineConfiguration': 'V-Shaped',
 'EngineCycles': '',
 'EngineCylinders': '6',
 'EngineHP': '240',
 'EngineHP_to': '',
 'EngineKW': '',
 'EngineManufacturer': '',
 'EngineModel': 'J30A4',
 'EntertainmentSystem': '',
 'ErrorCode': '0',
 'ErrorText': '0 - VIN decoded clean. Check Digit (9th position) is correct',
 'ForwardCollisionWarning': '',
 'FuelInjectionType': '',
 'FuelTankMaterial': '',
 'FuelTankType': '',
 'FuelTypePrimary': 'Gasoline',
 'FuelTypeSecondary': '',
 'GCWR': '',
 'GCWR_to': '',
 'GVWR': 'Class 1C: 4,001 - 5,000 lb (1,814 - 2,268 kg)',
 'GVWR_to': 'Class 1: 6,000 lb or less (2,722 kg or less)',
 'KeylessIgnition': '',
 'LaneCenteringAssistance': '',
 'LaneDepartureWarning': '',
 'LaneKeepSystem': '',
 'LowerBeamHeadlampLightSource': '',
 'Make': 'HONDA',
 'MakeID': '474',
 'Manufacturer': 'AMERICAN HONDA MOTOR CO., INC.',
 'ManufacturerId': '988',
 'Model': 'Accord',
 'ModelID': '1861',
 'ModelYear': '2003',
 'MotorcycleChassisType': 'Not Applicable',
 'MotorcycleSuspensionType': 'Not Applicable',
 'NCSABodyType': '',
 'NCSAMake': '',
 'NCSAMapExcApprovedBy': '',
 'NCSAMapExcApprovedOn': '',
 'NCSAMappingException': '',
 'NCSAModel': '',
 'NCSANote': '',
 'NonLandUse': '',
 'Note': '',
 'OtherBusInfo': '',
 'OtherEngineInfo': '',
 'OtherMotorcycleInfo': '',
 'OtherRestraintSystemInfo': 'Seat Belt (Rr center position)',
 'OtherTrailerInfo': '',
 'ParkAssist': '',
 'PedestrianAutomaticEmergencyBraking': '',
 'PlantCity': 'MARYSVILLE',
 'PlantCompanyName': '',
 'PlantCountry': 'UNITED STATES (USA)',
 'PlantState': 'OHIO',
 'PossibleValues': '',
 'Pretensioner': '',
 'RearAutomaticEmergencyBraking': '',
 'RearCrossTrafficAlert': '',
 'RearVisibilitySystem': '',
 'SAEAutomationLevel': '',
 'SAEAutomationLevel_to': '',
 'SeatBeltsAll': 'Manual',
 'SeatRows': '',
 'Seats': '',
 'SemiautomaticHeadlampBeamSwitching': '',
 'Series': '',
 'Series2': '',
 'SteeringLocation': '',
 'SuggestedVIN': '',
 'TPMS': '',
 'TopSpeedMPH': '',
 'TrackWidth': '',
 'TractionControl': '',
 'TrailerBodyType': 'Not Applicable',
 'TrailerLength': '',
 'TrailerType': 'Not Applicable',
 'TransmissionSpeeds': '5',
 'TransmissionStyle': 'Automatic',
 'Trim': 'EX-V6',
 'Trim2': '',
 'Turbo': '',
 'VIN': '1HGCM82633A004352',
 'ValveTrainDesign': 'Single Overhead Cam (SOHC)',
 'VehicleDescriptor': '1HGCM826*3A',
 'VehicleType': 'PASSENGER CAR',
 'WheelBaseLong': '',
 'WheelBaseShort': '',
 'WheelBaseType': '',
 'WheelSizeFront': '',
 'WheelSizeRear': '',
 'WheelieMitigation': '',
 'Wheels': '',
 'Windows': ''}

In [16]:
important_vehicle_info = {
    "make": vehicle.get("Make"),
    "model": vehicle.get("Model"),
    "year": vehicle.get("ModelYear"),
    "body_type": vehicle.get("BodyClass"),
}

important_vehicle_info

{'make': 'HONDA', 'model': 'Accord', 'year': '2003', 'body_type': 'Coupe'}

In [17]:
vehicle_year = int(important_vehicle_info["year"])

if vehicle_year < 2015:
    risk_level = "HIGH"
else:
    risk_level = "NORMAL"
risk_level

'HIGH'

In [18]:
clean_vehicle_info = {
    "make": vehicle.get("Make"),
    "model": vehicle.get("Model"),
    "year": vehicle.get("ModelYear"),
    "body_type": vehicle.get("BodyClass"),
}

clean_vehicle_info

{'make': 'HONDA', 'model': 'Accord', 'year': '2003', 'body_type': 'Coupe'}

In [19]:
import pandas as pd
contracts_df = pd.read_csv("../data/sample_car_contracts.csv")
contracts_df.head()

,id,customer_name,contract_type,vehicle_type,monthly_emi,interest_rate,tenure_months,clause_summary,risk_flag,issue_type,recommended_action
0,1,Rahul Mehta,Car Loan,Sedan,18500,9.5,48,Prepayment allowed only after 24 months with 5...,medium,High prepayment charges,Highlight prepayment penalty to user and sugge...
1,2,Anita Rao,Car Lease,SUV,22000,0.0,36,Lessee must pay for all maintenance and insurance,low,Standard maintenance clause,"No action, just explain maintenance responsibi..."
2,3,James Wilson,Car Loan,Hatchback,14500,11.2,60,Late payment fee of 3% per month on outstandin...,high,Aggressive late fee,Flag clause and suggest user request cap on la...
3,4,Meena Iyer,Car Lease,Sedan,21000,0.0,24,"Excess mileage charge of ₹12 per km over 15,00...",medium,High excess mileage rate,Warn user about extra mileage charges and reco...
4,5,Arjun Patel,Car Loan,SUV,27500,10.8,72,Floating interest rate linked to lender's inte...,high,Unclear interest benchmark,Explain floating rate risk and suggest asking ...

In [20]:
# Data Enrichment

def enrich_contract_with_vehicle(contract_row):
    contract_id = contract_row.get("contract_id")
    customer_name = contract_row.get("customer_name")
    vin = contract_row.get("vin")

    # If VIN is missing, do NOT call API
    if pd.isna(vin):
        return {
            "contract_id": contract_id,
            "customer_name": customer_name,
            "vin": None,
            "vehicle": None
        }

    vehicle = get_vehicle_details(vin)

    return {
        "contract_id": contract_id,
        "customer_name": customer_name,
        "vin": vin,
        "vehicle": {
            "make": vehicle.get("Make"),
            "model": vehicle.get("Model"),
            "year": vehicle.get("ModelYear")
        }
    }

In [21]:
combined_records = []

for _, row in contracts_df.iterrows():
    combined_records.append(enrich_contract_with_vehicle(row))

combined_records[:1]

[{'contract_id': None,
  'customer_name': 'Rahul Mehta',
  'vin': None,
  'vehicle': None}]

In [22]:
contracts_df.columns

Index(['id', 'customer_name', 'contract_type', 'vehicle_type', 'monthly_emi',
       'interest_rate', 'tenure_months', 'clause_summary', 'risk_flag',
       'issue_type', 'recommended_action'],
      dtype='object')

In [23]:
import pandas as pd 

contracts_df = pd.read_csv("../data/sample_car_contracts.csv")
contracts_df.head()

,id,customer_name,contract_type,vehicle_type,monthly_emi,interest_rate,tenure_months,clause_summary,risk_flag,issue_type,recommended_action
0,1,Rahul Mehta,Car Loan,Sedan,18500,9.5,48,Prepayment allowed only after 24 months with 5...,medium,High prepayment charges,Highlight prepayment penalty to user and sugge...
1,2,Anita Rao,Car Lease,SUV,22000,0.0,36,Lessee must pay for all maintenance and insurance,low,Standard maintenance clause,"No action, just explain maintenance responsibi..."
2,3,James Wilson,Car Loan,Hatchback,14500,11.2,60,Late payment fee of 3% per month on outstandin...,high,Aggressive late fee,Flag clause and suggest user request cap on la...
3,4,Meena Iyer,Car Lease,Sedan,21000,0.0,24,"Excess mileage charge of ₹12 per km over 15,00...",medium,High excess mileage rate,Warn user about extra mileage charges and reco...
4,5,Arjun Patel,Car Loan,SUV,27500,10.8,72,Floating interest rate linked to lender's inte...,high,Unclear interest benchmark,Explain floating rate risk and suggest asking ...

In [24]:
contracts_df["vin"] = "1HGCM82633A004352"

In [25]:
contracts_df[["vin"]].head()

                 vin
0  1HGCM82633A004352
1  1HGCM82633A004352
2  1HGCM82633A004352
3  1HGCM82633A004352
4  1HGCM82633A004352

In [26]:
contracts_df.to_csv("../data/sample_car_contracts_with_vin.csv", index=False)

In [27]:
def extract_sla_details(row):
    """
    Simulates LLM-based SLA extraction.
    Returns SLA details in JSON format.
    """
    return {
    "monthly_emi": row["monthly_emi"],
    "interest_rate": row["interest_rate"],
    "tenure_months": row["tenure_months"],
    "risk_flag": row["risk_flag"],
    "issue_type": row["issue_type"],
    "recommended_action": row["recommended_action"]
}

In [28]:
import pandas as pd

contracts_df = pd.read_csv("../data/sample_car_contracts_with_vin.csv")
contracts_df.head()

,id,customer_name,contract_type,vehicle_type,monthly_emi,interest_rate,tenure_months,clause_summary,risk_flag,issue_type,recommended_action,vin
0,1,Rahul Mehta,Car Loan,Sedan,18500,9.5,48,Prepayment allowed only after 24 months with 5...,medium,High prepayment charges,Highlight prepayment penalty to user and sugge...,1HGCM82633A004352
1,2,Anita Rao,Car Lease,SUV,22000,0.0,36,Lessee must pay for all maintenance and insurance,low,Standard maintenance clause,"No action, just explain maintenance responsibi...",1HGCM82633A004352
2,3,James Wilson,Car Loan,Hatchback,14500,11.2,60,Late payment fee of 3% per month on outstandin...,high,Aggressive late fee,Flag clause and suggest user request cap on la...,1HGCM82633A004352
3,4,Meena Iyer,Car Lease,Sedan,21000,0.0,24,"Excess mileage charge of ₹12 per km over 15,00...",medium,High excess mileage rate,Warn user about extra mileage charges and reco...,1HGCM82633A004352
4,5,Arjun Patel,Car Loan,SUV,27500,10.8,72,Floating interest rate linked to lender's inte...,high,Unclear interest benchmark,Explain floating rate risk and suggest asking ...,1HGCM82633A004352

In [29]:
sla_records = []
for _, row in contracts_df.iterrows():
    sla_records.append({
    "contract_id": row["id"],
    "customer_name": row["customer_name"],
    "sla": extract_sla_details(row)
    })
    
sla_df = pd.DataFrame(sla_records)
sla_df.head()

,contract_id,customer_name,sla
0,1,Rahul Mehta,"{'monthly_emi': 18500, 'interest_rate': 9.5, '..."
1,2,Anita Rao,"{'monthly_emi': 22000, 'interest_rate': 0.0, '..."
2,3,James Wilson,"{'monthly_emi': 14500, 'interest_rate': 11.2, ..."
3,4,Meena Iyer,"{'monthly_emi': 21000, 'interest_rate': 0.0, '..."
4,5,Arjun Patel,"{'monthly_emi': 27500, 'interest_rate': 10.8, ..."

In [30]:
sla_df.to_csv("../data/milestone2_sla_output.csv", index=False)

In [31]:
sla_df.sample(5)

,contract_id,customer_name,sla
7,8,Neha Singh,"{'monthly_emi': 25500, 'interest_rate': 0.0, '..."
6,7,Vikram Shah,"{'monthly_emi': 19500, 'interest_rate': 8.9, '..."
0,1,Rahul Mehta,"{'monthly_emi': 18500, 'interest_rate': 9.5, '..."
3,4,Meena Iyer,"{'monthly_emi': 21000, 'interest_rate': 0.0, '..."
8,9,David Roy,"{'monthly_emi': 30500, 'interest_rate': 12.5, ..."

In [32]:
import requests
def get_vehicle_details(vin):
    url =f"https://vpic.nhtsa.dot.gov/api/vehicles/DecodeVinValues/{vin}?format=json"
    response = requests.get(url)
    return response.json()["Results"][0]

In [33]:
def extract_vehicle_info(vehicle_raw):
    return {
    "make": vehicle_raw.get("Make"),
    "model": vehicle_raw.get("Model"),
    "year": vehicle_raw.get("ModelYear")
    }

In [34]:
def enrich_contract_with_vehicle(row):
    vehicle_raw = get_vehicle_details(row["vin"])
    vehicle_info = extract_vehicle_info(vehicle_raw)
    return {
        "contract_id": row["id"],
        "customer_name": row["customer_name"],
        "contract_type": row["contract_type"],
        "sla": extract_sla_details(row),
        "vehicle": vehicle_info
        }

In [35]:
combined_records = []
for _, row in contracts_df.iterrows():
    combined_records.append(enrich_contract_with_vehicle(row))
combined_df = pd.DataFrame(combined_records)
combined_df.head()

,contract_id,customer_name,contract_type,sla,vehicle
0,1,Rahul Mehta,Car Loan,"{'monthly_emi': 18500, 'interest_rate': 9.5, '...","{'make': 'HONDA', 'model': 'Accord', 'year': '..."
1,2,Anita Rao,Car Lease,"{'monthly_emi': 22000, 'interest_rate': 0.0, '...","{'make': 'HONDA', 'model': 'Accord', 'year': '..."
2,3,James Wilson,Car Loan,"{'monthly_emi': 14500, 'interest_rate': 11.2, ...","{'make': 'HONDA', 'model': 'Accord', 'year': '..."
3,4,Meena Iyer,Car Lease,"{'monthly_emi': 21000, 'interest_rate': 0.0, '...","{'make': 'HONDA', 'model': 'Accord', 'year': '..."
4,5,Arjun Patel,Car Loan,"{'monthly_emi': 27500, 'interest_rate': 10.8, ...","{'make': 'HONDA', 'model': 'Accord', 'year': '..."

In [36]:
combined_df.to_csv("../data/milestone2_evaluation_output.csv", index=False)