In [3]:
import pandas as pd
df=pd.read_csv('../data/batch2_contracts_125rows.csv')
df.head()

,contract_id,raw_text,apr,term_months,monthly_payment,penalty_clause,recommended_action,risk_flag
0,1,This contract between Prime Auto and Emily Sto...,10.49,24,959,NaN,Approve,Low
1,2,This contract between ABC Motors and Priya Sha...,3.78,24,804,Early termination fee $300,Approve,Low
2,3,This contract between DriveEasy Finance and Sa...,5.41,24,774,Late fee $50,Reject,High
3,4,This contract between National Motors and Alex...,5.26,48,1028,Late fee $25,Approve,High
4,5,This contract between National Motors and John...,5.97,36,1180,NaN,Approve,Low

In [4]:
df["expected_apr"] = df["apr"]
df["expected_term"] = df["term_months"]
df["expected_payment"] = df["monthly_payment"]
df["expected_penalty"] = df["penalty_clause"]

In [5]:
df.columns

Index(['contract_id', 'raw_text', 'apr', 'term_months', 'monthly_payment',
       'penalty_clause', 'recommended_action', 'risk_flag', 'expected_apr',
       'expected_term', 'expected_payment', 'expected_penalty'],
      dtype='object')

In [6]:
df[['penalty_clause',"expected_penalty"]]

                 penalty_clause            expected_penalty
0                           NaN                         NaN
1    Early termination fee $300  Early termination fee $300
2                  Late fee $50                Late fee $50
3                  Late fee $25                Late fee $25
4                           NaN                         NaN
..                          ...                         ...
120                Late fee $25                Late fee $25
121                Late fee $25                Late fee $25
122  Early termination fee $300  Early termination fee $300
123                         NaN                         NaN
124                Late fee $50                Late fee $50

[125 rows x 2 columns]

In [7]:
df["apr_score"] = (df["apr"]==df["expected_apr"]).astype(int)

df["term_score"] = (df["term_months"]==df["expected_term"]).astype(int)

df["payment_score"] = (df["monthly_payment"]==df["expected_payment"]).astype(int)

df["penalty_score"] = (df["penalty_clause"] == df["expected_penalty"]).astype(int)

df["total_score"] = (df["apr_score"] + df["term_score"] + df["payment_score"] + df["penalty_score"])

In [8]:
df["quality_score"] = (df["total_score"]/3) * 100

In [9]:
df[["apr_score" ,"term_score","payment_score","penalty_score","total_score","quality_score"]].head(20)

,apr_score,term_score,payment_score,penalty_score,total_score,quality_score
0,1,1,1,0,3,100.000000
1,1,1,1,1,4,133.333333
2,1,1,1,1,4,133.333333
3,1,1,1,1,4,133.333333
4,1,1,1,0,3,100.000000
5,1,1,1,0,3,100.000000
6,1,1,1,0,3,100.000000
7,1,1,1,1,4,133.333333
8,1,1,1,0,3,100.000000
9,1,1,1,1,4,133.333333
10,1,1,1,1,4,133.333333
11,1,1,1,0,3,100.000000
12,1,1,1,1,4,133.333333
13,1,1,1,1,4,133.333333
14,1,1,1,1,4,133.333333
15,1,1,1,1,4,133.333333
16,1,1,1,1,4,133.333333
17,1,1,1,1,4,133.333333
18,1,1,1,1,4,133.333333
19,1,1,1,0,3,100.000000