In [4]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv('milestone1_jyothsnasai.csv')
df.head()

,contract_id,raw_text,apr,term_months,monthly_payment,penalty_clause,risk_flag,recommended_action
0,1,This contract between Prime Auto and Emily Sto...,10.49,24,959,NaN,Low,Approve
1,2,This contract between ABC Motors and Priya Sha...,3.78,24,804,Early termination fee $300,Low,Approve
2,3,This contract between DriveEasy Finance and Sa...,5.41,24,774,Late fee $50,High,Reject
3,4,This contract between National Motors and Alex...,5.26,48,1028,Late fee $25,High,Approve
4,5,This contract between National Motors and John...,5.97,36,1180,NaN,Low,Approve

In [8]:
#Ground Truth simulation
df["expected_apr"] = df["apr"]
df["expected_term_months"] = df["term_months"]
df["expected_monthly_payment"] = df["monthly_payment"]
df["expected_penalty"] = df["penalty_clause"]

In [9]:
df = df.rename(columns={"penalty":"penalty_clause"})

In [10]:
df.columns

Index(['contract_id', 'raw_text', 'apr', 'term_months', 'monthly_payment',
       'penalty_clause', 'risk_flag', 'recommended_action', 'expected_apr',
       'expected_term_months', 'expected_monthly_payment', 'expected_penalty'],
      dtype='object')

In [11]:
df[["penalty_clause", "expected_penalty"]].head()

               penalty_clause            expected_penalty
0                         NaN                         NaN
1  Early termination fee $300  Early termination fee $300
2                Late fee $50                Late fee $50
3                Late fee $25                Late fee $25
4                         NaN                         NaN

In [17]:
# if extracted APR exactly matches expected
# APR Score 1
#if not score 0

# if extracted term months equals  expected
# term months Score 1
#else score 0

# if extracted penalty text matches expected
# penalty Score 1
# else score 0

df["apr_score"] = (df["apr"] ==df["expected_apr"]).astype(int)
df["term_months_score"] = (df["term_months"] ==df["expected_term_months"]).astype(int)
df["payment_score"] = (df["monthly_payment"] ==df["expected_monthly_payment"]).astype(int)
df["penalty_clause_score"] = (df["penalty_clause"] ==df["expected_penalty"]).astype(int)

df["total_score"] = df["apr_score"] + df["term_months_score"] + df["payment_score"] + df["penalty_clause_score"]
df["total_percentage"] = (df["total_score"] / 4) * 100
df[["apr_score", "term_months_score", "payment_score", "penalty_clause_score", "total_score", "total_percentage"]].head()

,apr_score,term_months_score,payment_score,penalty_clause_score,total_score,total_percentage
0,1,1,1,0,3,75.0
1,1,1,1,1,4,100.0
2,1,1,1,1,4,100.0
3,1,1,1,1,4,100.0
4,1,1,1,0,3,75.0

In [19]:
df.to_csv("../data/milestone2_jyothsna.csv",index=False)