In [3]:
import openai
print(openai.__version__)

2.15.0

In [5]:
import pandas as pd
import numpy as np
import requests

In [6]:
df = pd.read_csv("../data/milestone1_output_suresh.csv")
df.head(2)

,contract_id,extracted_text,apr,term_months,monthly_payment,penalty
0,1,This contract between Prime Auto and Emily Sto...,10.49,24,959,none
1,2,This contract between ABC Motors and Priya Sha...,3.78,24,804,early termination fee $300

In [8]:
# ================================
# Week 3 – LLM Prompt Design
# ================================

SLA_PROMPT_TEMPLATE = """
You are a legal contract analysis assistant specialized in car lease agreements.

Extract the following SLA details from the contract text.
If a value is missing, return null.
Return ONLY valid JSON. No explanation.

Fields:
- interest_rate_apr
- lease_term_months
- monthly_payment
- down_payment
- residual_value
- mileage_allowance
- overage_charge
- early_termination
- purchase_option
- maintenance_responsibility
- warranty_insurance
- penalties
- missing_or_ambiguous_clauses

Contract Text:
\"\"\"
{contract_text}
\"\"\"
"""

In [9]:
# ================================
# Week 3 – OpenAI LLM Extraction
# ================================



def extract_sla_with_gpt(contract_text):
    prompt = SLA_PROMPT_TEMPLATE.format(contract_text=contract_text)

    response = client.responses.create(
        model="gpt-4.1-mini",
        input=prompt
    )

    raw_output = response.output_text.strip()

    match = re.search(r"\{[\s\S]*\}", raw_output)
    if not match:
        return {"error": "No JSON found", "raw_output": raw_output}

    try:
        return json.loads(match.group(0))
    except Exception as e:
        return {"error": str(e), "json_text": match.group(0)}

In [10]:
test_output = extract_sla_with_gpt(df.loc[0,
"extracted_text"])
test_output

{'interest_rate_apr': 10.49,
 'lease_term_months': 24,
 'monthly_payment': 959,
 'down_payment': None,
 'residual_value': None,
 'mileage_allowance': None,
 'overage_charge': None,
 'early_termination': None,
 'purchase_option': None,
 'maintenance_responsibility': None,
 'warranty_insurance': None,
 'penalties': None,
 'missing_or_ambiguous_clauses': ['down_payment',
  'residual_value',
  'mileage_allowance',
  'overage_charge',
  'early_termination',
  'purchase_option',
  'maintenance_responsibility',
  'warranty_insurance',
  'penalties']}

In [13]:
# ================================
# Week 3 – Apply LLM & Store SLA
# ================================

sample_df = df.head(1)

sla_json_records = sample_df.apply(
    lambda row: {
        "contract_id": int(row.name),
        "sla": extract_sla_with_gpt(row["extracted_text"])
    },
    axis=1
).tolist()

sla_json_records[0]

# Store SLA JSON
with open("../data/milestone2_sla_output.json", "w") as f:
    json.dump(sla_json_records, f, indent=2)

print("SLA JSON stored successfully using OpenAI GPT")

SLA JSON stored successfully using OpenAI GPT

In [14]:
# ===============================
# Week 3 – Accuracy Evaluation (Sample Only)
# ===============================

# Use only 1 sample contract to avoid rate limits
eval_df = df.head(1).copy()

# Apply LLM extraction (SAFE – only 1 call)
eval_df["llm_sla"] = eval_df["extracted_text"].apply(extract_sla_with_gpt)

eval_df[["llm_sla"]]

                                             llm_sla
0  {'interest_rate_apr': '10.49%', 'lease_term_mo...

In [15]:
# Extract individual SLA fields from LLM output
eval_df["llm_apr"] = eval_df["llm_sla"].apply(lambda x: x.get("interest_rate_apr"))
eval_df["llm_term"] = eval_df["llm_sla"].apply(lambda x: x.get("lease_term_months"))
eval_df["llm_payment"] = eval_df["llm_sla"].apply(lambda x: x.get("monthly_payment"))

eval_df[["llm_apr", "llm_term", "llm_payment"]]

  llm_apr  llm_term  llm_payment
0  10.49%        24          959

In [16]:
# Ground truth values for sample contract (manual / known values)
eval_df["expected_apr"] = 10.49
eval_df["expected_term"] = 24
eval_df["expected_payment"] = 959

eval_df[[
    "llm_apr", "expected_apr",
    "llm_term", "expected_term",
    "llm_payment", "expected_payment"
]]

,llm_apr,expected_apr,llm_term,expected_term,llm_payment,expected_payment
0,10.49%,10.49,24,24,959,959

In [17]:
accuracy = {
    "APR Accuracy (%)": (eval_df["llm_apr"] == eval_df["expected_apr"]).mean() * 100,
    "Term Accuracy (%)": (eval_df["llm_term"] == eval_df["expected_term"]).mean() * 100,
    "Payment Accuracy (%)": (eval_df["llm_payment"] == eval_df["expected_payment"]).mean() * 100
}

accuracy

{'APR Accuracy (%)': np.float64(0.0),
 'Term Accuracy (%)': np.float64(100.0),
 'Payment Accuracy (%)': np.float64(100.0)}

In [18]:
# ===============================
# Week 4 – VIN Lookup (NHTSA API)
# ===============================

import requests

def fetch_vehicle_details_from_vin(vin):
    """
    Fetch vehicle make, model, year using NHTSA VIN Decode API
    """
    url = f"https://vpic.nhtsa.dot.gov/api/vehicles/DecodeVinValuesExtended/{vin}?format=json"
    response = requests.get(url, timeout=10)
    data = response.json()

    if not data.get("Results"):
        return None

    result = data["Results"][0]

    return {
        "vin": vin,
        "make": result.get("Make"),
        "model": result.get("Model"),
        "year": result.get("ModelYear")
    }

In [19]:
def fetch_vehicle_recalls(make, model, year):
    """
    Fetch recall information using NHTSA Recall API
    """
    if not make or not model or not year:
        return []

    url = (
        "https://api.nhtsa.gov/recalls/recallsByVehicle"
        f"?make={make}&model={model}&modelYear={year}"
    )

    response = requests.get(url, timeout=10)
    data = response.json()

    recalls = data.get("results", [])

    return [
        {
            "campaign_number": r.get("NHTSACampaignNumber"),
            "summary": r.get("Summary"),
            "consequence": r.get("Consequence")
        }
        for r in recalls
    ]

In [20]:
test_vin = "1HGCM82633A004352"

vehicle_info = fetch_vehicle_details_from_vin(test_vin)
vehicle_info

{'vin': '1HGCM82633A004352',
 'make': 'HONDA',
 'model': 'Accord',
 'year': '2003'}

In [21]:
recalls = fetch_vehicle_recalls(
    vehicle_info["make"],
    vehicle_info["model"],
    vehicle_info["year"]
)

recalls[:2]

[{'campaign_number': '19V182000',
  'summary': 'Honda (American Honda Motor Co.) is recalling specific 2003 Acura 3.2CL, 2013-2016 ILX, 2013-2014 ILX Hybrid, 2003-2006 MDX, 2007-2016 RDX, 2002-2003 3.2TL, 2004-2006, and 2009-2014 TL, 2010-2013 ZDX and 2001-2007 and 2009 Honda Accord, 2001-2005 Civic, 2003-2005 Civic Hybrid, 2001-2005 Civic GX NGV, 2002-2007 and 2010-2011 CR-V, 2003-2011 Element, 2007 Fit, 2002-2004 Odyssey, 2003-2008 Pilot, and 2006-2014 Ridgeline vehicles.  The affected vehicles received a replacement driver air bag inflator as part of a previous Takata inflator recall remedy or a replacement driver air bag module containing the same inflator type as a service part.  Due to a manufacturing error, in the event of a crash necessitating deployment of the driver frontal air bag, these inflators may explode.',
  'consequence': 'An explosion of an inflator within the driver frontal air bag module may result in sharp metal fragments striking the driver, front seat passenger or other occupants resulting in serious injury or death.'},
 {'campaign_number': '19E068000',
  'summary': 'Dorman Products, Inc.  (Dorman) is recalling certain Accelerator Pedal Assemblies part numbers 699-114 and 825-5029-1, sold as replacement parts for 2003-2006 Acura MDX, 2004-2008 Acura TL and TSX, 2003-2007 Honda Accord, 2005-2006 Honda CR-V, 2007-2011 Honda Element, 2005-2008 Honda Pilot and 2006-2014 Honda Ridgeline vehicles.  The rotating portion of the accelerator pedal assembly may bind. As such, these vehicles fail to comply with the requirements of Federal Motor Vehicle Safety Standard (FMVSS) number 124, "Accelerator Control Systems."',
  'consequence': 'If the accelerator pedal binds, the engine may not quickly return to idle after the pedal is no longer pressed, increasing the risk of a crash.'}]

In [22]:
# ===============================
# Week 4 – Combine SLA + Vehicle Data
# ===============================

def build_final_contract_response(contract_id, sla_data, vin):
    vehicle = fetch_vehicle_details_from_vin(vin)

    recalls = []
    if vehicle:
        recalls = fetch_vehicle_recalls(
            vehicle["make"],
            vehicle["model"],
            vehicle["year"]
        )

    return {
        "contract_id": contract_id,
        "sla": sla_data,
        "vehicle": vehicle,
        "recalls": recalls
    }

In [23]:
# Internal end-to-end test

sample_contract = sla_json_records[0]
sample_vin = "1HGCM82633A004352"

final_response = build_final_contract_response(
    contract_id=sample_contract["contract_id"],
    sla_data=sample_contract["sla"],
    vin=sample_vin
)

final_response

{'contract_id': 0,
 'sla': {'interest_rate_apr': 10.49,
  'lease_term_months': 24,
  'monthly_payment': 959,
  'down_payment': None,
  'residual_value': None,
  'mileage_allowance': None,
  'overage_charge': None,
  'early_termination': None,
  'purchase_option': None,
  'maintenance_responsibility': None,
  'warranty_insurance': None,
  'penalties': None,
  'missing_or_ambiguous_clauses': ['down_payment',
   'residual_value',
   'mileage_allowance',
   'overage_charge',
   'early_termination',
   'purchase_option',
   'maintenance_responsibility',
   'warranty_insurance',
   'penalties']},
 'vehicle': {'vin': '1HGCM82633A004352',
  'make': 'HONDA',
  'model': 'Accord',
  'year': '2003'},
 'recalls': [{'campaign_number': '19V182000',
   'summary': 'Honda (American Honda Motor Co.) is recalling specific 2003 Acura 3.2CL, 2013-2016 ILX, 2013-2014 ILX Hybrid, 2003-2006 MDX, 2007-2016 RDX, 2002-2003 3.2TL, 2004-2006, and 2009-2014 TL, 2010-2013 ZDX and 2001-2007 and 2009 Honda Accord, 2001-2005 Civic, 2003-2005 Civic Hybrid, 2001-2005 Civic GX NGV, 2002-2007 and 2010-2011 CR-V, 2003-2011 Element, 2007 Fit, 2002-2004 Odyssey, 2003-2008 Pilot, and 2006-2014 Ridgeline vehicles.  The affected vehicles received a replacement driver air bag inflator as part of a previous Takata inflator recall remedy or a replacement driver air bag module containing the same inflator type as a service part.  Due to a manufacturing error, in the event of a crash necessitating deployment of the driver frontal air bag, these inflators may explode.',
   'consequence': 'An explosion of an inflator within the driver frontal air bag module may result in sharp metal fragments striking the driver, front seat passenger or other occupants resulting in serious injury or death.'},
  {'campaign_number': '19E068000',
   'summary': 'Dorman Products, Inc.  (Dorman) is recalling certain Accelerator Pedal Assemblies part numbers 699-114 and 825-5029-1, sold as replacement parts for 2003-2006 Acura MDX, 2004-2008 Acura TL and TSX, 2003-2007 Honda Accord, 2005-2006 Honda CR-V, 2007-2011 Honda Element, 2005-2008 Honda Pilot and 2006-2014 Honda Ridgeline vehicles.  The rotating portion of the accelerator pedal assembly may bind. As such, these vehicles fail to comply with the requirements of Federal Motor Vehicle Safety Standard (FMVSS) number 124, "Accelerator Control Systems."',
   'consequence': 'If the accelerator pedal binds, the engine may not quickly return to idle after the pedal is no longer pressed, increasing the risk of a crash.'},
  {'campaign_number': '19V499000',
   'summary': 'Honda (American Honda Motor Co.) is recalling certain 2003 Acura 3.2CL, 2002-2003 3.2TL, 2003-2006 MDX, 2001-2007 Honda Accord, 2001-2005 Civic, 2003-2005 Civic Hybrid, 2001-2005 Civic GX NGV, 2002-2006 CR-V, 2003-2011 Element, 2002-2004 Odyssey, 2003-2008 Pilot and 2006 Ridgeline vehicles.  \r\n\r\nThese vehicles are equipped with driver frontal air bag inflators assembled as a recall remedy part or replacement service part, that may explode due to propellant degradation occurring after long-term exposure to high absolute humidity, temperature and temperature cycling.',
   'consequence': 'An inflator explosion may result in sharp metal fragments striking the driver or other occupants resulting in serious injury or death.'},
  {'campaign_number': '19V501000',
   'summary': 'Honda (American Honda Motor Co.) is recalling certain 2003-2006 Acura MDX, 2005-2012 RL, 2003-2007 Honda Accord, 2001-2005 Civic, 2003-2005 Civic Hybrid, 2001-2005 Civic GX NGV, 2002-2006 CR-V, 2003-2011 Element, 2007-2008 Fit, 2002-2004 Odyssey, 2003-2008 Pilot, and 2006-2014 Ridgeline vehicles. \r\n\r\nThe vehicles are equipped with passenger frontal air bag inflators assembled as a recall remedy part or replacement service part, that may explode due to propellant degradation occurring after long-term exposure to high absolute humidity, temperature and temperature cycling.',
   'consequence': 'An inflator explosion may result in sharp metal fragments striking the driver or other occupants resulting in serious injury or death.'},
  {'campaign_number': '18V268000',
   'summary': 'Honda (American Honda Motor Co.) is recalling certain 2003-2012 Honda Accord and Pilot, 2010 Accord Crosstour, 2001-2011 Civic, 2002-2011 CR-V, 2003-2004, 2006-2008 and 2011 Element, 2007 and 2009-2013 Fit, 2010-2012 Insight, 2002-2004 Odyssey, and 2012 Ridgeline vehicles.  The front passenger air bag may have been installed incorrectly during replacement.',
   'consequence': 'An incorrectly installed air bag may deploy improperly in the event of a crash, increasing the risk of injury.'},
  {'campaign_number': '17V220000',
   'summary': 'Honda (American Honda Motor Co.) is recalling certain 2003 Honda Accord Coupe vehicles, equipped with a four-cylinder engine.  If the passenger frontal air bag module has been replaced, such as after a crash necessitating frontal air bag deployment, the replacement air bag module may include a Takata air bag inflator.  These inflators may rupture due to propellant degradation occurring after long-term exposure to lower absolute humidity, temperature and temperature cycling.',
   'consequence': 'An inflator rupture may result in metal fragments striking the driver or other occupants resulting in serious injury or death.'},
  {'campaign_number': '15V320000',
   'summary': 'Honda (American Honda Motor Co.) is recalling certain model year 2001-2007 Accord, 2001-2005 Civic, 2001-2004 Honda Civic GX, 2003-2005 Honda Civic Hybrid, 2002-2006 CR-V, 2003-2011 Element, 2002-2004 Odyssey, 2003-2008 Pilot, 2006 Ridgeline, 2003 Acura 3.2CL, 2003-2006 Acura MDX, and 2002-2003 Acura 3.2TL vehicles.  The affected vehicles are equipped with a dual-stage driver frontal air bag that may be susceptible to moisture intrusion and other factors, including manufacturing variability that, over time, could cause the inflator to rupture.',
   'consequence': "In the event of a crash necessitating deployment of the driver's frontal air bag, the inflator could rupture with metal fragments striking the driver or other occupants resulting in serious injury or death."},
  {'campaign_number': '14V700000',
   'summary': 'American Honda Motor Co. (Honda) is recalling certain model year 2001-2005 Honda Civic, 2003-2004 Civic CNG and Element, 2002-2005 CR-V, 2002-2004 Odyssey, 2003-2005 Accord, Pilot, Civic Hybrid, and Acura MDX, 2005 Acura RL and 2006 Honda Ridgeline vehicles originally sold, or ever registered, in geographic locations associated with high absolute humidity.  Specifically, vehicles sold, or ever registered, in Alabama, Florida, Georgia, Hawaii, Louisiana, Mississippi, South Carolina, Texas, Puerto Rico, U.S. Virgin Islands, Saipan, Guam, and American Samoa are addressed by this recall.  Upon deployment of the passenger side frontal air bag, excessive internal pressure may cause the inflator to rupture.',
   'consequence': 'In the event of a crash necessitating deployment of the passenger\x92s frontal air bag, the inflator could rupture with metal fragments striking the vehicle occupants potentially resulting in serious injury or death.'},
  {'campaign_number': '15V370000',
   'summary': 'Honda (American Honda Motor Co.) is recalling certain model year 2001-2005 Honda Civic vehicles manufactured March 21, 2000, to January 20, 2005, 2001-2004 Honda Civic GX vehicles manufactured June 14, 2000, to August 19, 2004, 2003-2005 Honda Civic Hybrid vehicles manufactured February 24, 2002, to January 18, 2005, 2003-2007 Honda Accord vehicles manufactured February 21, 2002, to August 28, 2007, 2002-2004 Honda CR-V vehicles, 2002-2003 Honda Odyssey vehicles manufactured June 19, 2001, to July 12, 2003, 2003 Acura MDX vehicles manufactured September 19, 2002, to June 19, 2003, 2003 Honda Element vehicles manufactured June 25, 2002, to July 31, 2003, and 2003 Honda Pilot vehicles manufactured November 26, 2001, to August 21, 2003.  The affected vehicles have a passenger side frontal air bag that may be susceptible to moisture intrusion which, over time, could cause the inflator to rupture upon its deployment.',
   'consequence': "In the event of a crash necessitating deployment of the passenger's frontal air bag, the inflator could rupture with metal fragments striking the passenger seat occupant or other occupants possibly causing serious injury or death."},
  {'campaign_number': '14V353000',
   'summary': "American Honda Motor Company, Inc.'s (Honda) is conducting a limited regional recall for certain model year 2003-2005 Accord, Civic, CR-V, Pilot and Acura MDX, model year 2003-2004 Odyssey and Element, and model year 2005 Acura RL, and 2006 Honda Ridgeline vehicles originally sold, or ever registered in California, and equipped with Takata-brand air bag inflators.  Upon deployment of the passenger side frontal air bag, excessive internal pressure may cause the inflator to rupture.",
   'consequence': 'In the event of a crash necessitating deployment of the passenger\x92s frontal air bag, the inflator could rupture with metal fragments striking the vehicle occupants potentially resulting in serious injury or death.'},
  {'campaign_number': '08E050000',
   'summary': 'K2 MOTOR IS RECALLING 1,921 AFTERMARKET HEADLAMPS OF VARIOUS MODELS SOLD FOR USE ON THE ABOVE LISTED VEHICLES.  THESE HEADLAMPS ARE MISSING THE AMBER SIDE REFLEX REFLECTOR WHICH FAILS TO CONFORM WITH THE REQUIREMENTS OF FEDERAL MOTOR VEHICLE SAFETY STANDARD NO. 108, "LAMPS, REFLECTIVE DEVICES, AND ASSOCIATED EQUIPMENT."',
   'consequence': 'WITHOUT THE AMBER SIDE REFLEX REFLECTORS, THE LIGHTING VISIBILITY MAY BE AFFECTED, POSSIBLY RESULTING IN A VEHICLE CRASH.'},
  {'campaign_number': '09E012000',
   'summary': 'SABERSPORT IS RECALLING 16,270 COMBINATION CORNER AND BUMPER LAMP ASSEMBLIES OF VARIOUS PART NUMBERS SOLD FOR USE AS AFTERMARKET EQUIPMENT FOR VARIOUS PASSENGER VEHICLES.  THESE HEADLAMPS FAIL TO CONFORM TO THE REQUIREMENTS OF FEDERAL MOTOR VEHICLE SAFETY STANDARD NO. 108, "LAMPS, REFLECTIVE DEVICES, AND ASSOCIATED EQUIPMENT."  THESE LAMPS DO NOT CONTAIN THE REQUIRED AMBER SIDE REFLECTORS.',
   'consequence': 'DECREASED LIGHTING VISIBILITY MAY RESULT IN A VEHICLE CRASH.'},
  {'campaign_number': '12V222000',
   'summary': 'Honda is recalling certain model year 2007 and 2008 Acura TL and model year 2003-2007 Accord V6 vehicles.  In May 2012, Honda filed a defect report to recall certain model year 2007 and 2008 Acura TL vehicles.  In September 2012, Honda informed the agency that it was including an additional 573,147 vehicles including certain model year 2003 through 2007 Accord V6 vehicles.  The total number of vehicles being recalled is now 625,762.  Prolonged under-hood and power steering fluid temperatures may cause the power steering hose to deteriorate prematurely, resulting in cracks and power steering fluid leakage.',
   'consequence': 'If this occurs, power steering fluid can leak onto a hot catalytic converter, leading to smoke and possibly an under-hood fire.'},
  {'campaign_number': '06E038000',
   'summary': 'CERTAIN ALFAOTTO COMBINATION HEADLAMPS SOLD AS REPLACEMENT LAMPS FOR USE ON THE ABOVE LISTED PASSENGER VEHICLES.  SOME COMBINATION LAMPS THAT ARE NOT EQUIPPED WITH AMBER SIDE REFLECTORS FAIL TO CONFORM TO FEDERAL MOTOR VEHICLE SAFETY STANDARD NO. 108, LAMPS, REFLECTIVE DEVICES, AND ASSOCIATED EQUIPMENT.',
   'consequence': 'WITHOUT THE AMBER REFLECTORS, THE VEHICLE WILL BE POORLY ILLUMINATED, POSSIBLY RESULTING IN A VEHICLE CRASH WITHOUT WARNING.'},
  {'campaign_number': '10V364000',
   'summary': 'HONDA IS RECALLING CERTAIN MODEL YEAR 2003 HONDA ACCORD, CIVIC TWO AND FOUR DOOR, AND MODEL YEAR 2003-2004 HONDA ELEMENT VEHICLES.  THE INTERLOCK LEVER OF THE IGNITION SWITCH MAY UNEXPECTEDLY DEFORM, WHICH CAN ALLOW THE INTERLOCK FUNCTION OF A VEHICLE WITH AN AUTOMATIC TRANSMISSION TO BE DEFEATED.',
   'consequence': 'REMOVAL OF THE IGNITION KEY WHEN THE GEAR SELECTOR OF A VEHICLE WITH AN AUTOMATIC TRANSMISSION HAS NOT BEEN SHIFTED TO THE PARK POSITION CAN ALLOW THE VEHICLE TO ROLL AWAY, INCREASING THE RISK OF A CRASH.'},
  {'campaign_number': '06E023000',
   'summary': 'CERTAIN ANZO COMBINATION HEADLAMP ASSEMBLIES SOLD AS REPLACEMENT LAMPS FOR USE ON CERTAIN PASSENGER VEHICLES.  SOME COMBINATION LAMPS ARE NOT EQUIPPED WITH AMBER SIDE REFLECTORS WHICH FAIL TO CONFORM TO FEDERAL MOTOR VEHICLE SAFETY STANDARD NO. 108, "LAMPS, REFLECTIVE DEVICES, AND ASSOCIATED EQUIPMENT."',
   'consequence': 'WITHOUT THE AMBER REFLECTORS, THE VEHICLE WILL BE POORLY ILLUMINATED, POSSIBLY RESULTING IN A VEHICLE CRASH.'},
  {'campaign_number': '09E025000',
   'summary': 'DOPE, INC. IS RECALLING 42,540 COMBINATION CORNER AND BUMPER LAMP ASSEMBLIES OF VARIOUS PART NUMBERS SOLD FOR USE AS AFTERMARKET EQUIPMENT FOR VARIOUS PASSENGER VEHICLES.  THESE HEADLAMPS FAIL TO CONFORM TO THE REQUIREMENTS OF FEDERAL MOTOR VEHICLE SAFETY STANDARD NO. 108, "LAMPS, REFLECTIVE DEVICES, AND ASSOCIATED EQUIPMENT."  THESE LAMPS DO NOT CONTAIN THE REQUIRED AMBER SIDE REFLECTORS.',
   'consequence': 'DECREASED LIGHTING VISIBILITY MAY RESULT IN A VEHICLE CRASH.'},
  {'campaign_number': '07E004000',
   'summary': 'CERTAIN TYC HEADLAMP ASSEMBLIES P/NS 20-6361-00 AND 20-6362-00 SOLD AS AFTERMARKET EQUIPMENT FOR 2003-2006 HONDA ACCORD PASSENGER VEHICLES.  THE PHOTMETRIC WERE MISALIGNED WHICH DOES NOT COMPLY WITH FEDERAL MOTOR VEHICLE SAFETY STANDARD NO. 108, LAMPS, REFLECTIVE DEVICES, AND ASSOCIATED EQUIPMENT.',
   'consequence': 'MISALIGNMENT OF THE LIGHTS DEMINISHES FRONTAL ILLUMINATION WHICH COULD RESULT IN A VEHICLE CRASH.'},
  {'campaign_number': '06E064000',
   'summary': 'CERTAIN TRADESONIC COMBINATION LAMPS SOLD AS REPLACEMENT LAMPS FOR USE ON THE ABOVE LISTED PASSENGER VEHICLES.  COMBINATION LAMPS NOT EQUIPPED WITH AMBER SIDE REFLECTORS FAIL TO CONFORM WITH THE REQUIREMENTS OF FEDERAL MOTOR VEHICLE SAFETY STANDARD NO. 108, LAMPS, REFLECTIVE DEVICES, AND ASSOCIATED EQUIPMENT.',
   'consequence': 'LACK OF AMBER SIDE REFLECTORS IN THE LAMPS WILL DECREASE LIGHTING VISIBILITY TO OTHER DRIVERS AND MAY POSSIBLY RESULT IN A VEHICLE CRASH.'},
  {'campaign_number': '08V169000',
   'summary': 'HONDA IS RECALLING 351,000 MY 2003 ACCORD VEHICLES.  IF WATER ENTERS THE WINDSHIELD WIPER MOTOR BREATHER PORT, WHICH IS DESIGNED TO ALLOW THE MOTOR TO VENT WARM AIR DURING NORMAL OPERATION, IT CAN RESULT IN CORROSION INSIDE THE MOTOR HOUSING.  THIS  CAN CAUSE A FAILURE OF THE ELECTRICAL CIRCUIT BREAKER INSIDE THE MOTOR HOUSING.',
   'consequence': 'IF THE CIRCUIT BREAKER FAILS, IT WILL CAUSE THE WINDSHIELD WIPER MOTOR TO BECOME INOPERATIVE, WHICH CAN INCREASE THE LIKELIHOOD OF A CRASH IN CERTAIN CONDITIONS.'},
  {'campaign_number': '07E031000',
   'summary': 'CERTAIN MAXZONE HEADLIGHT ASSEMBLIES, DEPO BRAND, P/NOS. 317-1131L-AS, 317-1131R-AS, 317-1131L-US, AND 317-1131R-US, SOLD FOR USE AS AFTERMARKET EQUIPMENT FOR THE ABOVE LISTED PASSENGER VEHICLES.  DURING PRODUCTION A SLIGHT DISTORTION OF THE BEZEL CHANGED THE LUMINOUS INTENSITY OF THE TURN SIGNAL.  THESE HEADLAMPS FAIL TO CONFORM TO THE REQUIREMENTS OF FEDERAL MOTOR VEHICLE SAFETY STANDARD NO. 108, LAMPS, REFLECTIVE DEVICES, AND ASSOCIATED EQUIPMENT.',
   'consequence': 'DECREASED LIGHTING VISIBILITY MAY RESULT IN A VEHICLE CRASH.'},
  {'campaign_number': '06E025000',
   'summary': 'CERTAIN POLI-AUTO COMBINATION HEADLAMP ASSEMBLIES, P/NOS. 11-728, 11-728D, 11-710, 11-419, 11-713, 11-703, 11-704, 11-708P, 11-735, 11-725, 11-726, 11-716 (P&C), 11-721-1, 11-733, 11-729, 11-730, AND 11-732, SOLD AS REPLACEMENT LAMPS FOR USE ON CERTAIN PASSENGER VEHICLES.  SOME COMBINATION LAMPS THAT ARE NOT EQUIPPED WITH AMBER SIDE REFLECTORS FAIL TO CONFORM TO FEDERAL MOTOR VEHICLE SAFETY STANDARD NO. 108, "LAMPS, REFLECTIVE DEVICES, AND ASSOCIATED EQUIPMENT."',
   'consequence': 'WITHOUT THE AMBER REFLECTORS, THE VEHICLE WILL BE POORLY ILLUMINATED, POSSIBLY RESULTING IN A VEHICLE CRASH WITHOUT WARNING.'},
  {'campaign_number': '06E032000',
   'summary': 'CERTAIN EAGLE EYES AND SONAR HEADLIGHTS AND CORNER LIGHTS SOLD AS AFTERMARKET FOR USE ON 1988-2005 HONDA CIVIC, 1990-2005 HONDA ACCORD, AND 1990-2001 ACURA INTEGRA PASSENGER VEHICLES LISTED ABOVE.   HEADLIGHTS AND CORNER LIGHTS THAT ARE NOT EQUIPPED WITH AMBER SIDE REFLECTORS FAIL TO CONFORM TO FEDERAL MOTOR VEHICLE SAFETY STANDARD NO. 108, LAMPS, REFLECTIVE DEVICES, AND ASSOCIATED EQUIPMENT.',
   'consequence': 'WITHOUT THE AMBER REFLECTORS, THE VEHICLE WILL BE POORLY ILLUMINATED, POSSIBLY RESULTING IN A VEHICLE CRASH WITHOUT WARNING.'},
  {'campaign_number': '04V176000',
   'summary': 'ON SOME MINI VANS, SPORT UTILITY AND PASSENGER VEHICLES, CERTAIN OPERATING CONDITIONS CAN RESULT IN HEAT BUILD-UP BETWEEN THE COUNTERSHAFT AND SECONDARY SHAFT SECOND GEARS IN THE AUTOMATIC TRANSMISSION, EVENTUALLY LEADING TO GEAR TOOTH CHIPPING OR GEAR BREAKAGE.',
   'consequence': 'GEAR FAILURE COULD RESULT IN TRANSMISSION LOCKUP, WHICH COULD RESULT IN A CRASH.'}]}