In [11]:
import pandas as pd
df = pd.read_csv("../data/contract_evaluation_dataset_tulasi-vasireddy.csv")
df.head()

,contract_text,expected_apr,expected_term,expected_payment,expected_penalty
0,The loan agreement offers an APR of 8.5% for a...,8.5,36.0,310.0,Late payment penalty of $40
1,This car loan has an APR of 7.9% with a repaym...,7.9,48.0,275.0,NaN
2,The borrower agrees to a loan term of 60 month...,NaN,60.0,350.0,Penalty of 3% on delayed payments
3,The agreement specifies a loan duration of 24 ...,NaN,24.0,NaN,NaN
4,"In case of late payment, a fee of $100 will be...",NaN,NaN,NaN,Late fee of $100

In [12]:
expected_output = {
    "apr": None,
    "term_months": None,
    "monthly_payment": None,
    "penalty_clause": None
}

In [6]:
PROMPT = """
Extract ONLY the following fields from the contract text:
- APR
- Term in months
- Monthly payment
- Penalty clause

Rules:
- Return JSON only
- Return null if missing
- Do NOT infer values

Contract Text:
\"\"\"{contract_text}\"\"\"
"""

In [13]:
def extract_sla(contract_text):
    return {
        "apr": None,
        "term_months": None,
        "monthly_payment": None,
        "penalty_clause": None
    }

In [14]:
import pandas as pd

In [15]:
df = pd.read_csv("../data/contract_evaluation_dataset_tulasi-vasireddy.csv")
df.head()

,contract_text,expected_apr,expected_term,expected_payment,expected_penalty
0,The loan agreement offers an APR of 8.5% for a...,8.5,36.0,310.0,Late payment penalty of $40
1,This car loan has an APR of 7.9% with a repaym...,7.9,48.0,275.0,NaN
2,The borrower agrees to a loan term of 60 month...,NaN,60.0,350.0,Penalty of 3% on delayed payments
3,The agreement specifies a loan duration of 24 ...,NaN,24.0,NaN,NaN
4,"In case of late payment, a fee of $100 will be...",NaN,NaN,NaN,Late fee of $100

In [16]:
sample_df = df.head(5)
sample_df

,contract_text,expected_apr,expected_term,expected_payment,expected_penalty
0,The loan agreement offers an APR of 8.5% for a...,8.5,36.0,310.0,Late payment penalty of $40
1,This car loan has an APR of 7.9% with a repaym...,7.9,48.0,275.0,NaN
2,The borrower agrees to a loan term of 60 month...,NaN,60.0,350.0,Penalty of 3% on delayed payments
3,The agreement specifies a loan duration of 24 ...,NaN,24.0,NaN,NaN
4,"In case of late payment, a fee of $100 will be...",NaN,NaN,NaN,Late fee of $100

In [17]:
def extract_sla(contract_text):
    return {
        "apr": None,
        "term_months": None,
        "monthly_payment": None,
        "penalty_clause": None
    }

In [18]:
results = [extract_sla(text) for text in sample_df["contract_text"]]
results_df = pd.DataFrame(results)
results_df

    apr term_months monthly_payment penalty_clause
0  None        None            None           None
1  None        None            None           None
2  None        None            None           None
3  None        None            None           None
4  None        None            None           None

In [19]:
comparison_df = sample_df.reset_index(drop=True)

comparison_df["apr_match"] = (
    comparison_df["expected_apr"] == results_df["apr"]
).astype(int)

comparison_df["term_match"] = (
    comparison_df["expected_term"] == results_df["term_months"]
).astype(int)

comparison_df["payment_match"] = (
    comparison_df["expected_payment"] == results_df["monthly_payment"]
).astype(int)

comparison_df["penalty_match"] = (
    comparison_df["expected_penalty"] == results_df["penalty_clause"]
).astype(int)

comparison_df

,contract_text,expected_apr,expected_term,expected_payment,expected_penalty,apr_match,term_match,payment_match,penalty_match
0,The loan agreement offers an APR of 8.5% for a...,8.5,36.0,310.0,Late payment penalty of $40,0,0,0,0
1,This car loan has an APR of 7.9% with a repaym...,7.9,48.0,275.0,NaN,0,0,0,0
2,The borrower agrees to a loan term of 60 month...,NaN,60.0,350.0,Penalty of 3% on delayed payments,0,0,0,0
3,The agreement specifies a loan duration of 24 ...,NaN,24.0,NaN,NaN,0,0,0,0
4,"In case of late payment, a fee of $100 will be...",NaN,NaN,NaN,Late fee of $100,0,0,0,0