In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../data/milestone1_output_suresh.csv")
df.head()

,contract_id,extracted_text,apr,term_months,monthly_payment,penalty
0,1,This contract between Prime Auto and Emily Sto...,10.49,24,959,none
1,2,This contract between ABC Motors and Priya Sha...,3.78,24,804,early termination fee $300
2,3,This contract between DriveEasy Finance and Sa...,5.41,24,774,late fee $50
3,4,This contract between National Motors and Alex...,5.26,48,1028,late fee $25
4,5,This contract between National Motors and John...,5.97,36,1180,none

In [4]:
# Ground Truth Simulation

df["expected_apr"] = df["apr"]
df["expected_term"] = df["term_months"]
df["expeted_payment"] = df["monthly_payment"]
df["expected_penalty"] = df["penalty_clause"]

KeyError: 'penalty_clause'

In [5]:
df.columns

Index(['contract_id', 'extracted_text', 'apr', 'term_months',
       'monthly_payment', 'penalty', 'expected_apr', 'expected_term',
       'expeted_payment'],
      dtype='object')

In [6]:
df = df.rename(columns={"penalty": "penalty_clause"})

In [7]:
df.columns

Index(['contract_id', 'extracted_text', 'apr', 'term_months',
       'monthly_payment', 'penalty_clause', 'expected_apr', 'expected_term',
       'expeted_payment'],
      dtype='object')

In [9]:
df["expected_apr"] = df["apr"]
df["expected_term"] = df["term_months"]
df["expeted_payment"] = df["monthly_payment"]
df["expected_penalty"] = df["penalty_clause"]

In [10]:
df[["penalty_clause","expected_penalty"]].head()

               penalty_clause            expected_penalty
0                        none                        none
1  early termination fee $300  early termination fee $300
2                late fee $50                late fee $50
3                late fee $25                late fee $25
4                        none                        none

In [21]:
# if extracted APR exactly matches expected
# APR score 1
# if not score 0

# if extracted term months equals expected
# term months score 1
# else score 0

# if extracted penalty text matches expected
# penalty score 1
# else score 0

df["apr_score"] = (df["apr"] == df["expected_apr"]).astype(int)


df["term_score"] = (df["term_months"] == df["expected_term"]).astype(int)
df["penalty_score"] = (df["penalty_clause"] == df["expected_penalty"]).astype(int)

df["total_score"] = (df["apr_score"] + df["term_score"] + df["payment_score"] + df["penalty_score"])

KeyError: 'payment_score'

In [22]:
df["apr_score"] = (df["apr"] == df["expected_apr"]).astype(int)

In [23]:
df["term_score"] = (df["term_months"] == df["expected_term"]).astype(int)

In [24]:
df["penalty_score"] = (df["penalty_clause"] == df["expected_penalty"]).astype(int)

In [26]:
df["total_score"] = (df["apr_score"] + df["term_score"] + df["penalty_score"])

In [27]:
df["quality_percent"] = (df["total_score"]/3)*100

In [28]:
df[["apr_score","term_score","penalty_score","total_score","quality_percent"]].head()

   apr_score  term_score  penalty_score  total_score  quality_percent
0          1           1              1            3            100.0
1          1           1              1            3            100.0
2          1           1              1            3            100.0
3          1           1              1            3            100.0
4          1           1              1            3            100.0

In [31]:
df.to_csv("../data/milestone2_evaluation_output.csv",index=False)