In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/sample_car_contracts.csv')
df.head()

,id,customer_name,contract_type,vehicle_type,monthly_emi,interest_rate,tenure_months,clause_summary,risk_flag,issue_type,recommended_action
0,1,Rahul Mehta,Car Loan,Sedan,18500,9.5,48,Prepayment allowed only after 24 months with 5...,medium,High prepayment charges,Highlight prepayment penalty to user and sugge...
1,2,Anita Rao,Car Lease,SUV,22000,0.0,36,Lessee must pay for all maintenance and insurance,low,Standard maintenance clause,"No action, just explain maintenance responsibi..."
2,3,James Wilson,Car Loan,Hatchback,14500,11.2,60,Late payment fee of 3% per month on outstandin...,high,Aggressive late fee,Flag clause and suggest user request cap on la...
3,4,Meena Iyer,Car Lease,Sedan,21000,0.0,24,"Excess mileage charge of ₹12 per km over 15,00...",medium,High excess mileage rate,Warn user about extra mileage charges and reco...
4,5,Arjun Patel,Car Loan,SUV,27500,10.8,72,Floating interest rate linked to lender's inte...,high,Unclear interest benchmark,Explain floating rate risk and suggest asking ...

In [3]:
df.shape

(12, 11)

In [4]:
df.columns

Index(['id', 'customer_name', 'contract_type', 'vehicle_type', 'monthly_emi',
       'interest_rate', 'tenure_months', 'clause_summary', 'risk_flag',
       'issue_type', 'recommended_action'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  12 non-null     int64
 1   customer_name       12 non-null     object
 2   contract_type       12 non-null     object
 3   vehicle_type        12 non-null     object
 4   monthly_emi         12 non-null     int64
 5   interest_rate       12 non-null     float64
 6   tenure_months       12 non-null     int64
 7   clause_summary      12 non-null     object
 8   risk_flag           12 non-null     object
 9   issue_type          12 non-null     object
 10  recommended_action  12 non-null     object
dtypes: float64(1), int64(3), object(7)
memory usage: 1.2+ KB

In [9]:
df[['id','customer_name','contract_type','loan_amount','risk_level']].head(10)

KeyError: "['loan_amount', 'risk_level'] not in index"

In [6]:
df[['id','clause_summary']].head(10)

   id                                     clause_summary
0   1  Prepayment allowed only after 24 months with 5...
1   2  Lessee must pay for all maintenance and insurance
2   3  Late payment fee of 3% per month on outstandin...
3   4  Excess mileage charge of ₹12 per km over 15,00...
4   5  Floating interest rate linked to lender's inte...
5   6     Early termination fee equal to 6 months of EMI
6   7             No foreclosure charges after 12 months
7   8  Battery warranty covered only for 24 months or...
8   9  Mandatory bundled insurance from lender at non...
9  10  Security deposit of 3 EMIs, refundable at end ...

In [12]:

df[['monthly_emi','interest_rate','tenure_months']].describe()

        monthly_emi  interest_rate  tenure_months
count     12.000000      12.000000       12.00000
mean   20975.000000       5.233333       47.00000
std     5257.743208       5.536217       17.50844
min    13200.000000       0.000000       24.00000
25%    18000.000000       0.000000       36.00000
50%    20250.000000       4.450000       45.00000
75%    24750.000000      10.125000       51.00000
max    30500.000000      12.500000       84.00000

In [7]:
df.isna().sum()

id                    0
customer_name         0
contract_type         0
vehicle_type          0
monthly_emi           0
interest_rate         0
tenure_months         0
clause_summary        0
risk_flag             0
issue_type            0
recommended_action    0
dtype: int64

In [8]:
df['contract_type'].value_counts()

contract_type
Car Loan     6
Car Lease    6
Name: count, dtype: int64

In [9]:
df['risk_flag'].value_counts()

risk_flag
high      5
medium    4
low       3
Name: count, dtype: int64

In [10]:
# AVERAGE INTERESET RATE PER RISK LEVEL
df.groupby('risk_flag')['interest_rate'].mean()

risk_flag
high      6.900000
low       2.966667
medium    4.850000
Name: interest_rate, dtype: float64

In [13]:
df["tenure_years"] = df["tenure_months"] / 12
# df["total_amount"] = df["monthly_emi"] * df["tenure_months"]
# df["tenure_years" , "total_amount"].head()

avg_total = df.groupby('risk_flag')['total_amount'].mean()
print(avg_total)

risk_flag
high      1407000.0
low        683000.0
medium     812400.0
Name: total_amount, dtype: float64

In [15]:
df["total_amount"] = df["monthly_emi"] * df["tenure_months"]
avg_count_amount = df.groupby('risk_flag')['total_amount'].mean()
print(avg_count_amount)

risk_flag
high      1407000.0
low        683000.0
medium     812400.0
Name: total_amount, dtype: float64

In [19]:
cross = pd.crosstab(df['risk_flag'], df['recommended_action'])
print(cross)

recommended_action  Explain condition for refund, low risk  \
risk_flag
high                                                     0
low                                                      1
medium                                                   0

recommended_action  Explain floating rate risk and suggest asking for external benchmark or cap  \
risk_flag
high                                                                1
low                                                                 0
medium                                                              0

recommended_action  Flag as risky and suggest negotiating lower termination fee  \
risk_flag
high                                                                1
low                                                                 0
medium                                                              0

recommended_action  Flag as unfair tying and suggest independent insurance quote  \
risk_flag
high                                                                1
low                                                                 0
medium                                                              0

recommended_action  Flag clause and suggest user request cap on late fee  \
risk_flag
high                                                                1
low                                                                 0
medium                                                              0

recommended_action  Highlight cost and suggest user negotiate lower fee  \
risk_flag
high                                                                0
low                                                                 0
medium                                                              1

recommended_action  Highlight prepayment penalty to user and suggest negotiation for lower fee  \
risk_flag
high                                                                0
low                                                                 0
medium                                                              1

recommended_action  Mark as positive clause, no action required  \
risk_flag
high                                                          0
low                                                           1
medium                                                        0

recommended_action  No action, just explain maintenance responsibility to user  \
risk_flag
high                                                                0
low                                                                 1
medium                                                              0

recommended_action  Strongly warn user and recommend clarification / negotiation  \
risk_flag
high                                                                1
low                                                                 0
medium                                                              0

recommended_action  Warn user about battery risk and suggest extended warranty discussion  \
risk_flag
high                                                                0
low                                                                 0
medium                                                              1

recommended_action  Warn user about extra mileage charges and recommend realistic mileage estimate
risk_flag
high                                                                0
low                                                                 0
medium                                                              1