In [ ]:
#TASK1 
#Loading and Reading the Dataset
#Finding and Cleaning the Missing Values
#Filtering Based on Category
import pandas as pd

In [ ]:

df=pd.read_csv('../data/sample_car_contracts.csv')
df.head()

,id,customer_name,contract_type,vehicle_type,monthly_emi,interest_rate,tenure_months,clause_summary,risk_flag,issue_type,recommended_action
0,1,Rahul Mehta,Car Loan,Sedan,18500,9.5,48,Prepayment allowed only after 24 months with 5...,medium,High prepayment charges,Highlight prepayment penalty to user and sugge...
1,2,Anita Rao,Car Lease,SUV,22000,0.0,36,Lessee must pay for all maintenance and insurance,low,Standard maintenance clause,"No action, just explain maintenance responsibi..."
2,3,James Wilson,Car Loan,Hatchback,14500,11.2,60,Late payment fee of 3% per month on outstandin...,high,Aggressive late fee,Flag clause and suggest user request cap on la...
3,4,Meena Iyer,Car Lease,Sedan,21000,0.0,24,"Excess mileage charge of ₹12 per km over 15,00...",medium,High excess mileage rate,Warn user about extra mileage charges and reco...
4,5,Arjun Patel,Car Loan,SUV,27500,10.8,72,Floating interest rate linked to lender's inte...,high,Unclear interest benchmark,Explain floating rate risk and suggest asking ...

In [3]:
df.isnull().sum()

id                    0
customer_name         0
contract_type         0
vehicle_type          0
monthly_emi           0
interest_rate         0
tenure_months         0
clause_summary        0
risk_flag             0
issue_type            0
recommended_action    0
dtype: int64

In [ ]:
numeric=df.select_dtypes(include='number').columns
categorical=df.select_dtypes(include='object').columns
df[numeric]=df[numeric].fillna(df[numeric].mean())
df[categorical]=df[categorical].fillna(df[categorical].mode().iloc[0])

,id,customer_name,contract_type,vehicle_type,monthly_emi,interest_rate,tenure_months,clause_summary,risk_flag,issue_type,recommended_action
0,1,Rahul Mehta,Car Loan,Sedan,18500,9.5,48,Prepayment allowed only after 24 months with 5...,medium,High prepayment charges,Highlight prepayment penalty to user and sugge...
1,2,Anita Rao,Car Lease,SUV,22000,0.0,36,Lessee must pay for all maintenance and insurance,low,Standard maintenance clause,"No action, just explain maintenance responsibi..."
2,3,James Wilson,Car Loan,Hatchback,14500,11.2,60,Late payment fee of 3% per month on outstandin...,high,Aggressive late fee,Flag clause and suggest user request cap on la...
3,4,Meena Iyer,Car Lease,Sedan,21000,0.0,24,"Excess mileage charge of ₹12 per km over 15,00...",medium,High excess mileage rate,Warn user about extra mileage charges and reco...
4,5,Arjun Patel,Car Loan,SUV,27500,10.8,72,Floating interest rate linked to lender's inte...,high,Unclear interest benchmark,Explain floating rate risk and suggest asking ...
5,6,Sana Khan,Car Lease,Hatchback,16500,0.0,36,Early termination fee equal to 6 months of EMI,high,Heavy early termination penalty,Flag as risky and suggest negotiating lower te...
6,7,Vikram Shah,Car Loan,Sedan,19500,8.9,36,No foreclosure charges after 12 months,low,User friendly foreclosure policy,"Mark as positive clause, no action required"
7,8,Neha Singh,Car Lease,EV,25500,0.0,48,Battery warranty covered only for 24 months or...,medium,Limited EV battery warranty,Warn user about battery risk and suggest exten...
8,9,David Roy,Car Loan,SUV,30500,12.5,84,Mandatory bundled insurance from lender at non...,high,Forced insurance bundling,Flag as unfair tying and suggest independent i...
9,10,Kiran Kumar,Car Lease,Sedan,18500,0.0,30,"Security deposit of 3 EMIs, refundable at end ...",low,Standard security deposit,"Explain condition for refund, low risk"
10,11,Pratima Das,Car Loan,Hatchback,13200,9.9,48,"Processing fee of 1.5% of loan amount, non-ref...",medium,High processing fee,Highlight cost and suggest user negotiate lowe...
11,12,Imran Ali,Car Lease,SUV,24500,0.0,42,Lessor can repossess vehicle after 2 consecuti...,high,Aggressive repossession clause,Strongly warn user and recommend clarification...

In [14]:
suv = df[df['vehicle_type'] == "SUV"]
suv

,id,customer_name,contract_type,vehicle_type,monthly_emi,interest_rate,tenure_months,clause_summary,risk_flag,issue_type,recommended_action
1,2,Anita Rao,Car Lease,SUV,22000,0.0,36,Lessee must pay for all maintenance and insurance,low,Standard maintenance clause,"No action, just explain maintenance responsibi..."
4,5,Arjun Patel,Car Loan,SUV,27500,10.8,72,Floating interest rate linked to lender's inte...,high,Unclear interest benchmark,Explain floating rate risk and suggest asking ...
8,9,David Roy,Car Loan,SUV,30500,12.5,84,Mandatory bundled insurance from lender at non...,high,Forced insurance bundling,Flag as unfair tying and suggest independent i...
11,12,Imran Ali,Car Lease,SUV,24500,0.0,42,Lessor can repossess vehicle after 2 consecuti...,high,Aggressive repossession clause,Strongly warn user and recommend clarification...

In [15]:
suv_sedan = df[df['vehicle_type'].isin(["SUV", "Sedan"])]
suv_sedan

,id,customer_name,contract_type,vehicle_type,monthly_emi,interest_rate,tenure_months,clause_summary,risk_flag,issue_type,recommended_action
0,1,Rahul Mehta,Car Loan,Sedan,18500,9.5,48,Prepayment allowed only after 24 months with 5...,medium,High prepayment charges,Highlight prepayment penalty to user and sugge...
1,2,Anita Rao,Car Lease,SUV,22000,0.0,36,Lessee must pay for all maintenance and insurance,low,Standard maintenance clause,"No action, just explain maintenance responsibi..."
3,4,Meena Iyer,Car Lease,Sedan,21000,0.0,24,"Excess mileage charge of ₹12 per km over 15,00...",medium,High excess mileage rate,Warn user about extra mileage charges and reco...
4,5,Arjun Patel,Car Loan,SUV,27500,10.8,72,Floating interest rate linked to lender's inte...,high,Unclear interest benchmark,Explain floating rate risk and suggest asking ...
6,7,Vikram Shah,Car Loan,Sedan,19500,8.9,36,No foreclosure charges after 12 months,low,User friendly foreclosure policy,"Mark as positive clause, no action required"
8,9,David Roy,Car Loan,SUV,30500,12.5,84,Mandatory bundled insurance from lender at non...,high,Forced insurance bundling,Flag as unfair tying and suggest independent i...
9,10,Kiran Kumar,Car Lease,Sedan,18500,0.0,30,"Security deposit of 3 EMIs, refundable at end ...",low,Standard security deposit,"Explain condition for refund, low risk"
11,12,Imran Ali,Car Lease,SUV,24500,0.0,42,Lessor can repossess vehicle after 2 consecuti...,high,Aggressive repossession clause,Strongly warn user and recommend clarification...

In [9]:
emi_above_20k = df[df['monthly_emi'] > 20000]
emi_above_20k

,id,customer_name,contract_type,vehicle_type,monthly_emi,interest_rate,tenure_months,clause_summary,risk_flag,issue_type,recommended_action
1,2,Anita Rao,Car Lease,SUV,22000,0.0,36,Lessee must pay for all maintenance and insurance,low,Standard maintenance clause,"No action, just explain maintenance responsibi..."
3,4,Meena Iyer,Car Lease,Sedan,21000,0.0,24,"Excess mileage charge of ₹12 per km over 15,00...",medium,High excess mileage rate,Warn user about extra mileage charges and reco...
4,5,Arjun Patel,Car Loan,SUV,27500,10.8,72,Floating interest rate linked to lender's inte...,high,Unclear interest benchmark,Explain floating rate risk and suggest asking ...
7,8,Neha Singh,Car Lease,EV,25500,0.0,48,Battery warranty covered only for 24 months or...,medium,Limited EV battery warranty,Warn user about battery risk and suggest exten...
8,9,David Roy,Car Loan,SUV,30500,12.5,84,Mandatory bundled insurance from lender at non...,high,Forced insurance bundling,Flag as unfair tying and suggest independent i...
11,12,Imran Ali,Car Lease,SUV,24500,0.0,42,Lessor can repossess vehicle after 2 consecuti...,high,Aggressive repossession clause,Strongly warn user and recommend clarification...

In [16]:
suv_emi_above_25k = df[(df['vehicle_type'] == "SUV") & (df['monthly_emi'] > 25000)]
suv_emi_above_25k

,id,customer_name,contract_type,vehicle_type,monthly_emi,interest_rate,tenure_months,clause_summary,risk_flag,issue_type,recommended_action
4,5,Arjun Patel,Car Loan,SUV,27500,10.8,72,Floating interest rate linked to lender's inte...,high,Unclear interest benchmark,Explain floating rate risk and suggest asking ...
8,9,David Roy,Car Loan,SUV,30500,12.5,84,Mandatory bundled insurance from lender at non...,high,Forced insurance bundling,Flag as unfair tying and suggest independent i...