In [1]:
import pandas as pd
df = pd.read_csv("milestone1_sriharini.csv")

In [2]:
import numpy as np

In [3]:
df.head()

,Unnamed: 0,contract_id,raw_text,apr,term_months,monthly_payment,penalty_clause,recommended_action,risk_flag
0,0,1,This contract between Prime Auto and Emily Sto...,10.49,24,959,NaN,Approve,Low
1,1,2,This contract between ABC Motors and Priya Sha...,3.78,24,804,Early termination fee $300,Approve,Low
2,2,3,This contract between DriveEasy Finance and Sa...,5.41,24,774,Late fee $50,Reject,High
3,3,4,This contract between National Motors and Alex...,5.26,48,1028,Late fee $25,Approve,High
4,4,5,This contract between National Motors and John...,5.97,36,1180,NaN,Approve,Low

In [4]:
df.columns

Index(['Unnamed: 0', 'contract_id', 'raw_text', 'apr', 'term_months',
       'monthly_payment', 'penalty_clause', 'recommended_action', 'risk_flag'],
      dtype='object')

In [5]:
df = df.rename(columns={"penalty": "penalty_clause"})

In [6]:
df["expected_apr"] = df["apr"]
df["expected_term"] = df["term_months"]
df["expeted_payment"] = df["monthly_payment"]
df["expected_penalty"] = df["penalty_clause"]

In [7]:
df[["penalty_clause","expected_penalty"]].head()

               penalty_clause            expected_penalty
0                         NaN                         NaN
1  Early termination fee $300  Early termination fee $300
2                Late fee $50                Late fee $50
3                Late fee $25                Late fee $25
4                         NaN                         NaN

In [8]:
# if extracted APR exactly matches expected
# APR score 1
# if not score 0

# if extracted term months equals expected
# term months score 1
# else score 0

# if extracted penalty text matches expected
# penalty score 1
# else score 0

df["apr_score"] = (df["apr"] == df["expected_apr"]).astype(int)

In [9]:
df["term_score"] = (df["term_months"] == df["expected_term"]).astype(int)

In [10]:
df["penalty_score"] = (df["penalty_clause"] == df["expected_penalty"]).astype(int)

In [11]:
df["total_score"] = (df["apr_score"] + df["term_score"] + df["penalty_score"])

In [12]:
df["quality_percent"] = (df["total_score"]/3)*100
df[["apr_score","term_score","penalty_score","total_score","quality_percent"]].head()

   apr_score  term_score  penalty_score  total_score  quality_percent
0          1           1              0            2        66.666667
1          1           1              1            3       100.000000
2          1           1              1            3       100.000000
3          1           1              1            3       100.000000
4          1           1              0            2        66.666667